### ISSUE TITLE
Ignore scammers with low prices

### ISSUE THREAD

**Issue by IceLancerSR** [domialex/Sidekick#10]
trade macro has ability to ignore such. "remove multiple listings by same account" the removed item is also removed from average and median price calc

Its effective in removing all those scammers which lists items cost 1 alteration,1 jeweler etc

**Comment by domialex** [comment]
It's a must of course!

**Comment by domialex** [comment]
Making this medium priority since there are now a lot of traders who refuse to trade, so users might want to ignore them.

**Comment by leMicin** [comment]
Similar to #128 .

**Comment by leMicin** [comment]
As per #128 :
This is not in the scope of this project at the moment. We are showing what is avaiable in the trade market from the official API. We are not currently interested in doing analytics to show what price is right or wrong.
