### ISSUE TITLE
Ctrl+D not working

### ISSUE THREAD

**Issue by thedarker03** [domialex/Sidekick#109]
Ctrl F and tab scrolling are working fine, but Ctrl D and F5 are not working at all
Game is in Widowed FS
Suggestions?

**Comment by domialex** [comment]
Can you copy the [log of Sidekick](https://i.imgur.com/RSrucuC.png) after you've pressed Ctrl+D on an item? Also, can you Ctrl+C on the item you're trying to price check and copy your clipboard here?

**Comment by thedarker03** [comment]
17/01/2020 01:04:52 - Starting Sidekick.
17/01/2020 01:06:19 - Fetching Path of Exile trade data.
17/01/2020 01:06:27 - Fetching Leagues.
17/01/2020 01:08:01 - 4   Leagues fetched.
17/01/2020 01:08:01 - Fetching Static item categories.
17/01/2020 01:08:01 - 31  Static item categories fetched.
17/01/2020 01:08:01 - Fetching Attribute categories.
17/01/2020 01:08:02 - 9   Attribute categories fetched.
17/01/2020 01:08:02 - Fetching Item categories.
17/01/2020 01:08:03 - 13  Item categories fetched.
17/01/2020 01:08:03 - Path of Exile trade data fetched.
17/01/2020 01:08:03 - Sidekick is ready, press Ctrl+D over an item in-game to use. Press Escape to close overlay.

This is the log of sidekick, seems like it doesn t receive the imput

**Comment by domialex** [comment]
@thedarker03 Test with [POE-TradeMacro](https://github.com/PoE-TradeMacro/POE-TradeMacro) please. If Ctrl+C doesn't work, you probably have something blocking that. Ctrl+C in Path of Exile is a normal in-game function that copies the item to your clipboard.

**Comment by leMicin** [comment]
Closing this as we don't have any updates for 3 weeks
