### ISSUE TITLE
Use System.Text.Json instead of Newtonsoft

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#111]

**Comment by Blinke** [comment]
I had a quick look at this and was disappointed to find some missing functionality in `System.Text.Json` [regarding dictionaries](https://github.com/dotnet/corefx/issues/40120). We are currently using enums as keys in `Settings.cs` which is not supported out of the box.

There are workarounds but unless there's something we really need from the new library they seem like more trouble than they're worth.

**Comment by domialex** [comment]
In another project I also hit some walls with System.Text.Json.

**Comment by leMicin** [comment]
I am working on this, can I be assigned to let other developpers know?

**Comment by leMicin** [comment]
There remains a dependency inside the Sidekick project because of the way the settings are handled. This will be fixed by #132 . I consider this issue done.

If there are any remaining issues regarding dictionaries, please open a new bug. It will probably be additional serializer configurations.

**Comment by domialex** [comment]
I'll close it with #132 at the same time.

**Comment by leMicin** [comment]
With #167 , we have no dependencies with Newtonsoft.Json anymore.
