### ISSUE TITLE
Expand .editorconfig for consistent code style

### ISSUE THREAD

**Issue by JadedCricket** [domialex/Sidekick#114]

**Comment by leMicin** [comment]
Throwing this here. Here is the .editorconfig for the source code of AspNetCore/Mvc as an exemple.

https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/.editorconfig

**Comment by leMicin** [comment]
Also, here is the microsoft docs regarding this:
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017

**Comment by JadedCricket** [comment]
That aspnetcore .editorconfig is a great starting point. We can use that one and just add new rules whenever we see a conflict pop up.

**Comment by domialex** [comment]
I always prefer to use `var` unless it's explicitly needed. If the variable's name can't speak for itself, it's not a good sign.

**Comment by leMicin** [comment]
I will do this task. I will take the aspnetcore config as a starting point. We will be able to adjust it in the future.
