### ISSUE TITLE
Use HttpClientFactory

### ISSUE THREAD

**Issue by JadedCricket** [domialex/Sidekick#115]
Since we are going the dependency injection route I think we should probably look into using the HttpClientFactory. Microsoft recommends this over a singleton and we leave all the intricacies of HttpClient resource management to them. 

Specifically, I think we should create typed clients. Then we don't have to pass the base url in with each request so it will clean things up a bit.

Some light reading:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1

**Comment by domialex** [comment]
Related to #86. I also use the client factory in .Net Core and I think it's clean.

**Comment by leMicin** [comment]
I am working in integrating this now.

**Comment by domialex** [comment]
Implemented with #123.
