### ISSUE TITLE
Item Wiki cannot be opened when map is not normal rarity

### ISSUE THREAD

**Issue by cmos12345** [domialex/Sidekick#117]
Rarity: Rare
Barren Frontier
Malformation Map
--------
Map Tier: 16
Item Quantity: +85% (augmented)
Item Rarity: +38% (augmented)
Monster Pack Size: +25% (augmented)
Quality: +20% (augmented)
--------
Item Level: 84
--------
Area contains many Totems
Monsters have 386% increased Critical Strike Chance
+43% to Monster Critical Strike Multiplier
Monsters deal 107% extra Damage as Cold
Monsters gain an Endurance Charge on Hit
Players have Point Blank
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

This does not work for example

**Comment by Zalhera** [comment]
Did you use Poe Wiki or Poe Db?

**Comment by cmos12345** [comment]
Tested it with both

**Comment by domialex** [comment]
On develop or v0.3.0?

**Comment by cmos12345** [comment]
On develop. Didn't try it with 0.3.0

**Comment by leMicin** [comment]
I may have broken this with my latest PR. The map data fetcher code is not called anymore. I am fixing this.

**Comment by domialex** [comment]
Fixed by #118.
