### ISSUE TITLE
Price checking issue Fragments

### ISSUE THREAD

**Issue by MOSHR00M97** [domialex/Sidekick#12]
When I try to price check any fragments (Scarabs, Boss Frags etc.) the program shows the prices for every item on market (showing 20items out of 200000) starting with 1 jeweller's orb.
![issue](https://user-images.githubusercontent.com/59592172/71867563-e8007700-310a-11ea-8901-527c26fb0ade.PNG)

**Comment by Yureii** [comment]
The same happens with cards. Here is a Price of Loyalty (arround 70c) I just got and it shows the same.
![Price of loyalty 1 alt](https://user-images.githubusercontent.com/7841011/71928896-bb933c00-3198-11ea-9f9b-1e31314d73c4.png)

**Comment by Zalhera** [comment]
Fragments and Divination Cards can now be checked with the correct price.

**Comment by domialex** [comment]
Closes #28
