### ISSUE TITLE
Feature Request: Flask Macro

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#120]
It would basicly be custom macro that could have 5 auto button presses at max after 1 button press.

example:
1-2 are HP flasks
3 - 5 are Utility flasks
When you press 3 - it will trigger 4 and 5 aswell ( all of the utility flasks at once )

So the set up would like this in this case:
trigger key: "3"
triggered key 1: "4"
triggered key 2: "5"
triggered key 3: 
triggered key 4:

There is a moral issue with this, but this is very common to use.

**Comment by JadedCricket** [comment]
This is again Path of Exile TOS. It's not gonna happen

**Comment by AwesomeFart** [comment]
in that case pls revome this - i am sorry, its so common - did not realize.

**Comment by domialex** [comment]
I'm also not a fan of macros, gotta play the game the way it was meant to be played! lol
