### ISSUE TITLE
Add a hotkey to show cheatsheets

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#122]
MercuryTrade has this and I used it often.

**Comment by lascoin** [comment]
Yes I use the overlay in tradecompanion it has all the league specific ones
Incursion
Betrayal
Delve

**Comment by leMicin** [comment]
I like this idea! +1

**Comment by bgriffs** [comment]
This guy has some nice images for all the league based stuff. Maybe they could be used.

https://github.com/kestalkayden/League-Overlay

**Comment by domialex** [comment]
We could add an overlay that would have multiple tabs, navigating left and right between them could be done quickly with the scroll wheel.
We just weed @kestalkayden's permission to use those nice images.

**Comment by domialex** [comment]
Started with #149.

**Comment by Zalhera** [comment]
Finished with #162

**Comment by domialex** [comment]
@Zalhera There are still some adjustments that I want to add before closing.

**Comment by Zalhera** [comment]
@domialex I will try to implement these fixes in the next couple of days

**Comment by Zalhera** [comment]
Done with #174
