### ISSUE TITLE
Detect listings that are off the median

### ISSUE THREAD

**Issue by Jinuskeya** [domialex/Sidekick#128]
Next to the in-game Whisper function I came up with a new idea. Would it be possible to change the text color for price fixers? The criteria to show a price fixer would be to;

- An items has been listed for more than an 'x' amount of days for the lowest price and hasn't sold.
- A player has reported the player for a price fixer via the Sidekick tool. 

The font of the listed item would than be changed to a red 'alert' color to warn players that they might list their items cheaper than the actual market value (good for new players) or they should be wary for e.g. the starforge/voidforge scam.

**Comment by domialex** [comment]
Sidekick already shows the age of the listed item. Instead, I was thinking of maybe using colors (green and red) somewhere on the line to highlight that this listing is completely off the median and let the user judge if it's a price fixer/good deal.

I don't like having Sidekick making decisions **based on probabilities**. For example having a big red text saying "this guy is a price fixer" is too extreme in opinion.

Also, I don't think price fixing is a reportable offense for GGG.

**Comment by leMicin** [comment]
This is not in the scope of this project at the moment. We are showing what is avaiable in the trade market from the official API. We are not currently interested in doing analytics to show what price is right or wrong.
