### ISSUE TITLE
Option to see items' stats in the listing on hover

### ISSUE THREAD

**Issue by ZzZombo** [domialex/Sidekick#129]
* An option to load next page, as well as to return one page back, and a quick link to go the first.
* Option to see items' stats in the listing on hover.
* A button to close the window by mouse.

**Comment by domialex** [comment]
- [x] An option to load next page, as well as to return one page back, and a quick link to go the first. #102  
- [ ] Option to see items' stats in the listing on hover.
- [x ] A button to close the window by mouse. Duplicate of #106.

**Comment by domialex** [comment]
Can be updated with a real UserControl in the future.
