### ISSUE TITLE
Rewrite settings

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#132]
# Goals
- Use IConfiguration interface to get the settings.
- Have property getters for all configurations. This can get verbose in the code, but it will also be very easy to hook onto the configuration values.
- Make the configuration available to all projects.

**Comment by leMicin** [comment]
As mentioned in #167 , The keybind settings page is not working and needs to be fixed.

I also want to redesign the general settings to have a scrollable list of settings similar to how the keybinds were instead of being arbitrarily placed into blocks.

**Comment by cmos12345** [comment]
Poe Wiki settings currently cannot be saved, as the UI does not synchronize with the settings object
