### ISSUE TITLE
Show the price check overlay instantly and load data asynchronously

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#141]
The Api calls should be done async and not block the overlay from being shown.
1. Ctrl+D item
2. Parse item -> success
3. Show overlay with only the item info
4. Populate PoeApi results
5. Populate poe.ninja for uniques | Populate poeprices.info for rares

**Comment by leMicin** [comment]
This is now easily feasible with the viewModel pattern shown with #132
