### ISSUE TITLE
Implement Dependency Injection for our views and view models

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#144]
Here is a start on how one could accomplish this.
https://stackoverflow.com/questions/54877352/dependency-injection-in-net-core-3-0-for-wpf

# Goals
- Remove the Legacy.cs file completely from the Sidekickk project.

# Views
- [x] Logs
- [x] League overlay
- [x] Price check
- [x] Settings
- [x] Splash screen
- [x] Tray icon

**Comment by Blinke** [comment]
We should definitely find a good way to do this. Another, broader question is how to handle instantiation and management of windows in general.

Right now that's handled by various static classes which is not great in the long run. I was thinking of setting up some sort of windows manager that is responsible for keeping track of the different views and their view models. It would be able to be injected in other classes and provide easy, structured access to the windows without the tight coupling of the static classes.

**Comment by leMicin** [comment]
This has been started with 0.4 for the settings view. The objective is to complete all views for 0.5

**Comment by Blinke** [comment]
The tray icon part was done with #226
