### ISSUE TITLE
Not supported russian language

### ISSUE THREAD

**Issue by Zuboskalik** [domialex/Sidekick#146]
v0.3.0 beta description:
> Now supports every Path of Exile language (might have some bugs)

using 0.3.0 from Releases page

Playing on russian locale selected

When tried to use - nothing happens

When opened log - "Path of Exile language not supported yet"

**Comment by domialex** [comment]
Thanks, this is probably already fixed in the development version, but still present in the v0.3.0-beta.
Just to be sure, can you Ctrl+C the item in-game and paste it here?
