### ISSUE TITLE
Items are Low price or Wrong price

### ISSUE THREAD

**Issue by CabirSurucu** [domialex/Sidekick#15]

**Comment by Martacus** [comment]
This is a useless issue since it doesn't provide any information whatsoever other than. It's broken. 

Provide the item name, stats, calculated costs and actual costs. Without it it probably will be very hard to resolve, if at all.

**Comment by domialex** [comment]
This is probably the user expecting Sidekick to make a price prediction in my opinion. Closing since it's not a reasonable feature.
Related to #63 and #79.
