### ISSUE TITLE
Hotkeys should be optional

### ISSUE THREAD

**Issue by GoneTesting** [domialex/Sidekick#152]
The ability to have f5 hideout scroll and the others should have the option to be disabled in case people are using these for other things

**Comment by cmos12345** [comment]
This is already implemented in the development version. At least for the hotkeys. I think you cannot yet disable the StashScroll. 
Most of it will be available to everyone with the next release

**Comment by domialex** [comment]
Duplicate of #7. Scroll+Wheel indeed needs to be configurable.
