### ISSUE TITLE
Implement Resource files as a replacement for the UILanguageProvider

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#157]
# Goals
- Completely remove the UILanguageProvider to use Resource files instead
- Support the fact that not all content will be translated in all languages at all times. It should fall back to the English language.
- Isolate the UI language files in a new project Sidekick.Localization
- The LanguageProvider used for parsing is unchanged for the time being.

# References
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1

**Comment by Blinke** [comment]
I think the new project should be called something like Sidekick.Localization instead of UI. The latter seems too broad and nonspecific. Otherwise I agree with this suggestion!

**Comment by leMicin** [comment]
Edited, good point :)
