### ISSUE TITLE
Implement Item Checker ( Ctrl+C from TradeMacro)

### ISSUE THREAD

**Issue by Derasm** [domialex/Sidekick#163]
As title says. 
Item checker is the one that checks what quality does on skill gems, and what the DPS is on the checked item.
I've been looking into how it is done, by copying an item to the clipboard and using it from there. However i wasn't able to figure it out, and as such will make a request for it instead.

**Comment by leMicin** [comment]
Any reason for the quick close?

**Comment by domialex** [comment]
If we show the [selected item's info in the main overlay](https://i.imgur.com/i0xPSem.png), it's the same feature.
