### ISSUE TITLE
Price checking conqueror orbs does not work

### ISSUE THREAD

**Issue by potato404** [domialex/Sidekick#179]
when i ctrl+d on crusaders exalted orb or an awakeners orb nothing happens

**Comment by leMicin** [comment]
Which version are you using?

0.3 or using the development version?

**Comment by domialex** [comment]
This is happening because Crusader's Exalted Orbs have **Currency** as their rarity, which is not true because it's not in the [static data](https://www.pathofexile.com/api/trade/data/static) but in the [item categories](https://www.pathofexile.com/api/trade/data/items).

```
Rarity: Currency
Crusader's Exalted Orb
--------
Stack Size: 1/10
--------
Adds Crusader influence and a new Crusader modifier to a rare item
--------
Right click this item then left click a high-level rare item with no influence to apply it. Rare items can have up to six random modifiers. The item's Catalyst quality increases the chance of applying a modifier which matches the quality type. Removes 20% Quality applied by Catalysts on use.
--------
Note: ~price 188 chaos
```
