### ISSUE TITLE
Price check of un-sealed prophecies

### ISSUE THREAD

**Issue by iTob191** [domialex/Sidekick#197]
It would be great if you could check prophecies while they are not sealed as an item but applied to your character. Not sure if this is possible though.

**Comment by cmos12345** [comment]
I‘m pretty sure that this is impossible, because it is not supported by GGG (you don‘t get any text to parse, as long as the prophecies are unsealed)

**Comment by leMicin** [comment]
In that case, we can't do it. It would have been cool.

**Comment by iTob191** [comment]
Okay, thanks anyway.

**Comment by domialex** [comment]
I wouldn't say it's impossible, there's always a way.

One would be to launch a macro that would move the mouse around all the prophecies (or manually hover the prophecies) on your menu and detect the prophecy with some OCR. Sidekick would need to save the position and the prophecy name. When a prophecy is completed, next time the prophecy menu is shown, same thing, we detect what's missing.

Anways, it's still possible, probably not very needed.
