### ISSUE TITLE
Wrong price

### ISSUE THREAD

**Issue by Yokoharu** [domialex/Sidekick#20]
Inspecting an item gives wrong price
![image](https://user-images.githubusercontent.com/17888383/71897082-c8427080-3155-11ea-9dc8-c33ce21c4e5e.png)
The real price is closer to 15 chaos.

**Comment by sceiler** [comment]
Probably because it supports only unique items at the moment

**Comment by Yokoharu** [comment]
ah, sorry, i thought unique means item with unique names, like non-rare, sorry!

**Comment by Yokoharu** [comment]
ah, sorry, i thought unique means item with unique names, like non-rare, sorry!
