### ISSUE TITLE
Add a scale setting to support high resolution monitors

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#204]

**Comment by leMicin** [comment]
With .Net Core, the WPF windows are supposed to automatically adjust with the DPI. Is this issue still valid since 0.5.0?

**Comment by objmj-itminds** [comment]
Hi 

I think my issue is somewhat related, so I would say that it is still active.

I am using version 0.7.2 and this is the placement of my window on a 4k monitor

https://i.imgur.com/UTq6SlM.jpg

**Comment by domialex** [comment]
@objmj-itminds This should be fixed in the next release, v0.8.0.

**Comment by leMicin** [comment]
With v 0.8.0+, the scale setting of windows affects the Sidekick text. If the text is too small for you, adjust your Windows settings.
