### ISSUE TITLE
Update the Betrayal overlay

### ISSUE THREAD

**Issue by Ricardo1701** [domialex/Sidekick#206]
Currently, the betrayal overlay being used is outdated, and shows wrong information, for example, it shows that Vagan only gives Rare things, however, now he gives Legion stuff

Here is an updated chart: https://i.imgur.com/WPhwKL9.png

**Comment by leMicin** [comment]
Thanks for the feedback, we will update it for 0.5. We don't have an ETA yet. But 0.5 is a very small release compared to 0.4.

**Comment by Zalhera** [comment]
Updated with #210

**Comment by leMicin** [comment]
Our colors do not match the updated chart. There is still work to be done here.

**Comment by leMicin** [comment]
The data has been updated in #216 . We still need to review after the pull request is merged.

**Comment by leMicin** [comment]
Resolved by #216
