### ISSUE TITLE
Pricecheck shows offline offers since 0.4

### ISSUE THREAD

**Issue by jenixavire** [domialex/Sidekick#211]
Ever since the update sidekick only shows totally irrelevant and outdated offers of offline people - it is not usable at this point.

![grafik](https://user-images.githubusercontent.com/60901936/74194412-7a8bbd00-4c59-11ea-880b-daeecd0d7331.png)

**Comment by jenixavire** [comment]
**
![grafik](https://user-images.githubusercontent.com/60901936/74194597-dbb39080-4c59-11ea-83ef-b58fee15a71c.png)
![grafik](https://user-images.githubusercontent.com/60901936/74194628-ecfc9d00-4c59-11ea-9303-1968cd356264.png)

**

**Comment by domialex** [comment]
Thank you for creating the issue.
