### ISSUE TITLE
Add multiple language support for poe.ninja

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#217]
Poe.ninja now supports 8 languages.
Adding `&language=fr`, for example, gives a `translations` dictionary at the end of the response. Can be tedious to find a clean way to use this.

**Comment by leMicin** [comment]
It should't be too hard. The value we want is the LanguageProvider one. And the PoeNinjaCache already has a hook to OnAfterInit. When we change language, the initializer runs so it should update all the data.
