### ISSUE TITLE
Price Checking Bulk Sales

### ISSUE THREAD

**Issue by Tornac** [domialex/Sidekick#23]
One feature that I always missed in the original trade macro was to check bulk sales.
Example: Rusted Breach Scarabs are 1c right now if you set minimum stock to 1, but 1.5-2c if you set minimum stock to 20.
However, this uses a different enpoint: https://www.pathofexile.com/trade/exchange

**Comment by cmos12345** [comment]
I'm on this, but I think for now, I can only implement, that currency will always be searched via the exchange endpoint. If we are able to configure the tool more then we can implement the minimum stock sizes etc.

**Comment by Tornac** [comment]
> I'm on this, but I think for now, I can only implement, that currency will always be searched via the exchange endpoint. If we are able to configure the tool more then we can implement the minimum stock sizes etc.

I've started working on this too, directly using the exchange api. It seems though that while the /trade/exchange has very similar response types, they're not identical.
In the end I just had to duplicate a lot of code, and I haven't even started adding to the UI yet.
If I get a usable result, I'll definitely submit a PR.

**Comment by cmos12345** [comment]
I think the main difference is the way you have to build the request. 
For the results you can use most of the classes from the normal search API. The only real difference being the price class I think.
I was also thinking about implementing a simple interface(IBulkSearchable or sth like this) to identify item types that could be searched via the bulk exchange API.

**Comment by domialex** [comment]
Implemented with #37. If we need a more advanced usage we'll make another issue.
