### ISSUE TITLE
[Trade] Show chaos equivalent price as a tooltip

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#233]
This is a continuation of #50

**Comment by domialex** [comment]
Should also limit the precision:
https://i.imgur.com/XndpTz5.png

**Comment by leMicin** [comment]
The precision issue is going to be fixed via #144 .

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
