### ISSUE TITLE
Sort columns in price view

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#234]

**Comment by leMicin** [comment]
Did this exist before?

**Comment by domialex** [comment]
Nope lol.

**Comment by leMicin** [comment]
Should this be an enhancement then? :P

**Comment by leMicin** [comment]
Removed sorting for now (#235 ) as the sort would be executed on the API as we do not have the full data. This is a nice enhancement for the future.

**Comment by leMicin** [comment]
I don't think it makes sense to sort any other way than Price (Lowest to highest) in the trade (price) view.
