### ISSUE TITLE
Add customizable hotkeys to switch tabs

### ISSUE THREAD

**Issue by KjetilSvends** [domialex/Sidekick#256]

**Comment by Blinke** [comment]
Could you elaborate on how you'd like this to work? PoE trade macro is made with AutoHotKey which makes adding custom scripts easy. It's not as straightforward in C#.

**Comment by KjetilSvends** [comment]
Didnt realize it was written in C#. Personally I loathe scrolling with mousewheel (tabs) and have added the following to custommacros in poetradmacro

#Ifwinactive, Path of Exile

~a::
    SendInput, {Left}
~d::  
   SendInput, {Right}
return

**Comment by domialex** [comment]
So basically you want to customise which hotkey scrolls the inventory tabs.

**Comment by KjetilSvends** [comment]
thats my use case, yes.

Dunno what others used custom macros for.

**Comment by leMicin** [comment]
I added the keybinds. By default, there are no keybinds for Scrolling left or right, you will need to set them up yourself once we release 0.5.0 later this week.
