### ISSUE TITLE
Invalid/inactive league can be saved in the settings

### ISSUE THREAD

**Issue by jezznar** [domialex/Sidekick#259]
tool tip is not working after the update

**Comment by leMicin** [comment]
Thanks for the report. We might not fix this for 0.4.0. We are working on releasing 0.5.0 later this week for delirium. So it will be at most a few days of wait.

**Comment by jezznar** [comment]
Please ignore this report. After checking my settings, I just realized that metamorph league is already over hence I needed to change to standard league.

**Comment by leMicin** [comment]
Thanks for letting us know :)

**Comment by leMicin** [comment]
Reopening this as we need to handle the fact that the league is no longer active. If the league is no longer active we need to select the first of the available leagues automatically.

This needs to be done before delirium is out to cause minimal issues for users that are updating.

**Comment by jezznar** [comment]
awesome :)
