### ISSUE TITLE
Servers are down - Stuck on "Initializing (2 of 3)" on first launch

### ISSUE THREAD

**Issue by Newbrict** [domialex/Sidekick#261]
![image](https://user-images.githubusercontent.com/1683041/76643646-ddf45d80-652b-11ea-9526-017b319c185b.png)

any idea what the problem is? Using the latest version x64, win10.

**Comment by Panzerhandschuh** [comment]
I'm getting the same problem.

**Comment by domialex** [comment]
The servers are down, which Sidekick needs in order to work. It's intended.

**Comment by Blinke** [comment]
We should probably try to display some sort of error message instead of freezing indefinitely though.

**Comment by leMicin** [comment]
@Blinke Totally agree

**Comment by pobiega** [comment]
This is because`PoeApiClient` has `await Task.Delay(TimeSpan.FromMinutes(1));` in it. I suggest the retry gets shortened to maybe 10 seconds and that it only tries twice before erroring out.

**Comment by leMicin** [comment]
@pobiega Noted inside #262 . Thanks :)
