### ISSUE TITLE
Display error feedback when errors occur during initialization

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#262]
# Goals

- [x] Add a button to close the application
- [x] Add a button to show logs inside the splashscreen view
- [x] Show clear feedback when an error occurs
- [x] Shorten the retry to 10 seconds
- [x] Do not try more than 2 or 3 times
- [x] Fail the initialization gracefully

Related to #261

**Comment by Newbrict** [comment]
Also, please add ability to close the window if it is stuck, it seems I have to use task manager at the moment...
