### ISSUE TITLE
Google and Windows reports Sidekick as unsafe

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#265]
We need to figure out why

**Comment by leMicin** [comment]
We have solved the warning from Google Chrome, but Windows still warns about our software.

**Comment by leMicin** [comment]
Does anybody still experience this issue?

**Comment by Frost117** [comment]
Yeah, just got the warning when I ran it for the first time

**Comment by leMicin** [comment]
This is still an issue with 0.7.2. If anybody has any ideas on how to fix this. Please let us know!

**Comment by tris790** [comment]
Are you guys signing the executable ? If not windows is probably flagging it as suspicious since it has no reputation. More info [here](https://docs.microsoft.com/en-us/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates)

**Comment by domialex** [comment]
I'm going to close this, since honestly, code signing is way too expensive 🤷‍♂️.
