### ISSUE TITLE
No more slot information after the update?

### ISSUE THREAD

**Issue by jezznar** [domialex/Sidekick#267]
Hi is it intentional for the slot information to be removed after the update?
![image](https://user-images.githubusercontent.com/13676977/76684973-10e14300-664b-11ea-8d14-2a9f69da1329.png)

**Comment by leMicin** [comment]
Do you mean sockets? Sockets were never shown on the preview or the list results. We will try to add them in the near future. Thanks for the comment :)

**Comment by jezznar** [comment]
@leMicin eeerr I think I remember having them in the tooltip that shows something like **R-R-G-B-W**

**Comment by leMicin** [comment]
I created #275 to implement this feature. I think it will be done pretty quickly, thanks for the feedback.
