### ISSUE TITLE
Closing UI with mouse click does not work

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#268]
Closing overlay with mouse click does not work - the option in the menu does not make any difference when turned off/on
I run Sidekick as administrator

Its the same with CTRL +Scroll - it just works without the option being turned on or off ( maybe the game itself has it now? idk )

**Comment by leMicin** [comment]
For the Ctrl+Scroll, the game itself has it if you have the mouse over your tabs. Sidekick allows you to use Ctrl+Scroll even when you are not over the stash (inventory, or center screen)

As for the Mouse click, it is indeed a bug. Thanks for the report

**Comment by domialex** [comment]
The thing is that originally, Sidekick was able to prevent sending the original Ctrl+Scroll event, so the game wouldn't do it twice. It would be nice if we could make it work again.

**Comment by leMicin** [comment]
@domialex Exactly my thoughts, we (I) probably broke this when we restructured the project.
