### ISSUE TITLE
Price checking divination cards does not work again from divination card stash tab

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#273]
it the same bug as 2 versions before, i think it was already in the last version - its still in 5.1

**Comment by domialex** [comment]
Duplicate of #84. It's not a bug, it's **impossible**.
The only way I can think that could make this work, is with OCR. https://i.imgur.com/xjKzRiv.png

Which would also allow us in the future to have Prophecy detection.

@leMicin How do we treat this issue? (feature?)

**Comment by leMicin** [comment]
I think this would be a very complex task for very little gain. I would simply close this issue. I suggest reporting a bug with GGG and asking to allow Ctrl+C in the divination tab.

**Comment by AwesomeFart** [comment]
Ok, i just tested this with TradeMacro - does not work either, meh i guess.. Kinda sux tho.. when i have 100 cards in divination stash tab and simply want to check if some are valuable - i have to pull all of the 100 cards to my inventory... but yeah i get it.
