### ISSUE TITLE
Auto-Update

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#274]
The way it was done in .Net Framework does not work anymore. We also do not need to backup files anymore since it is only one file.

References #264

**Comment by leMicin** [comment]
We need to discuss if we want this feature back. Broken auto-updates are a pain for users. Directing them to the latest download may be the best option. Discuss

**Comment by bgriffs** [comment]
As an end user I'd much rather have an auto update that occasionally doesn't work and asks me to download than something that never auto updates. The convenience outweighs the risk.
