### ISSUE TITLE
Crash when price checking magic items

### ISSUE THREAD

**Issue by iTob191** [domialex/Sidekick#278]
I can reliably reproduce the stuttering followed by Sidekick crashing described [here](https://github.com/domialex/Sidekick/issues/276#issuecomment-599290131) by price checking a magic cluster jewel. When you do so, Sidekick first shows the "Unable to find prices for this item" window, then Windows is stuttering for a few seconds and when it's over Sidekick is gone.
I tried watching the log during this procedure, but it disappears as soon as I start price checking anything.

Version: v0.5.2-beta

**Comment by leMicin** [comment]
Thanks for the report. We are working on a completely new item parser for 0.6.0. We will make sure this bug does not happen anymore. We plan on releasing 0.6.0 this week.

**Comment by leMicin** [comment]
This is fixed by #243
