### ISSUE TITLE
Language setting not working initially

### ISSUE THREAD

**Issue by iTob191** [domialex/Sidekick#279]
My system language is German and I have configured Sidekick to use English instead. After starting Sidekick most of its UI elements (right-click menu, price check window, cheatsheet, keybindings tab of settings) are in German though. The only element that correctly displays in English is the general tab of the settings window.
Once I open the settings window (without changing anything and without closing it), everything switches to English.

Version: v0.5.2-beta

**Comment by leMicin** [comment]
Thanks for the report. We will fix it this week for 0.6.0
