### ISSUE TITLE
stuck on checking prices

### ISSUE THREAD

**Issue by knasen88** [domialex/Sidekick#281]
sometimes it never manage to finish searching for an item and get stuck, a manual cancel bind would be nice
https://i.imgur.com/ZX38j9H.png
probably related to #276 
to reproduce in my specific case, price search a 12% qual caustic arrow, but it intermittently happens on random (probably less) searched items

**Comment by leMicin** [comment]
Can you close the window while the search is active?

**Comment by knasen88** [comment]
nah it never comes up, and cant be closed, new update and it doesn't break on the same gem atleast. ill try play around more if i can recreate it again

**Comment by leMicin** [comment]
@knasen88 Have you reproduced this error since 0.6.0?

**Comment by knasen88** [comment]
yes it happened the other day and become unresponsive, had to force close and restart. playing more tomorrow will try to reproduce. 
All the log gives is just "check prices" and then stops functioning, doesn't crash per say but simply stop working. sadly can't shadowplay since i disabled it due to delirium performance

**Comment by knasen88** [comment]
#294 describes the same issue, doesn't crash just becomes passive after some searches

**Comment by leMicin** [comment]
We will then keep the discussion going in #294 . So we don't have duplicate issues. Thanks for the report.
