### ISSUE TITLE
Make windows/panels resizable

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#285]
# Resizable windows
- [x] Splash screen
- [x] Price view
- [ ] ~~League view~~
- [x] Settings (vertical only)
- [x] Logs

**Comment by bgriffs** [comment]
With the ability to resize windows being able to change the default size scaling in the settings would be a huge benefit. Gives a better starting point.

**Comment by leMicin** [comment]
It will not be possible to resize the league view as all the tabs have different sizes. We could have a way of detecting the tab and resizing then, but I think this is out of scope for this current issue. Related to #386
