### ISSUE TITLE
Add property filters to the price view

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#289]
- [x] Item Level
  - [x] Enabled by default if iLvl >= 86
- [x] Armor 
- [x] EnergyShield
- [x] Block chance
- [x] Evasion 
- [x] Quality 
- [x] Level 
- [x] ItemQuantity
- [x] ItemRarity
- [x] MonsterPackSize
- [x] Blighted
- [x] ElementalDamage
- [x] CriticalStrikeChance
- [x] AttacksPerSecond
- [x] PhysicalDamage
- [x] Influences
- [x] Corrupted
- [x] Non-corrupted

**Comment by Newbrict** [comment]
can you add influence to this list

**Comment by leMicin** [comment]
Influences are automatically included, but yeah I agree, it should be available to select / unselect
