### ISSUE TITLE
Port to .NET Core and try to make Sidekick cross-platform

### ISSUE THREAD

**Issue by jonstelly** [domialex/Sidekick#29]
I've converted the project to the new CSPROJ format [here](https://github.com/jonstelly/Sidekick/commits/feature/dotnetcore).  If nothing else I think the new csproj files are easier to read.

EDIT: And can dramatically reduce merge conflicts in the csproj files.
 
But it might be nice to target .net core 3.0 to allow for [single exe builds](https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/) and to remove a dependency for users to install .NET 4.8.

There are two things blocking that:

1. There are a couple dependencies on System.Windows.Forms (context menu, tray icon, etc...) that would need to be replaced
2. [MouseKeyHook](https://github.com/gmamaladze/globalmousekeyhook) would need to be ported to .net core or .net standard.  I haven't dug into MouseKeyHook yet but I'll try to do that some time this week.

If there's interest in merging this, I can submit a pull request.

I can also throw together a quick Github Actions build if that might be helpful?

**Comment by domialex** [comment]
There is a lot of interest, I wanted to be able to make this cross-platform.
✔- WPF can be easily replaced by https://github.com/AvaloniaUI/Avalonia
❌- Keyboard and mouse hooks I've no idea how to make it cross-platform.
✔- Clipboard management should be supporte by https://github.com/SimonCropp/TextCopy

**Comment by Lev0r** [comment]
@domialex I think you will need to create as many KeyboardService realizations as many platforms you want to support. But, if we will isolate it well enough and create simple interface, it should not be hard to add a new platform.

**Comment by domialex** [comment]
I will need help for this if possible.

**Comment by jonstelly** [comment]
Pull request submitted.  I'll dig into the MouseKeyHook library and see what sort of effort it would be to port it.

I see two steps for how to look at building for .net core:

First would be to get the app working as-is using WPF and on Windows only, but running as a .net core app which gives the self contained single executable option and removes the .NET Framework dependency for users.

The second step would be to go after Linux and/or Mac support, porting the UI to something like Avalon and getting the keyboard and mouse hooks working on Linux / Mac.

I don't think the first step will be a lot of work but the second could be a sizable effort.

**Comment by MrAdam** [comment]
Seems like somebody ported MouseKeyHook to .NET Core 3.0 already, if it helps you:
https://github.com/topstarai/WindowsHook

**Comment by domialex** [comment]
@jonstelly Still on-board? A lot of work has been done to separate the project's UI from the logic.

**Comment by jonstelly** [comment]
@domialex I'm probably going to be swamped with work for the foreseeable future.  I'll try to pick up something next time I get some free time.  But Sidekick is coming along nicely, keep it up!

**Comment by domialex** [comment]
@jonstelly No problem! I just wanted to make sure we weren't stepping on something you might've already  been working on.
