### ISSUE TITLE
Hotkeys don't work after a failed query

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#294]
To keep track I'm creating this issue, but I don't have all the information to reproduce. It seems that after an error that doesn't crash Sidekick, it doesn't handle hotkeys correctly until we restart it (might be something else that's blocking it, clipboard, windows, etc.).

**Comment by leMicin** [comment]
I believe this could be related to #325

**Comment by domialex** [comment]
From what I've read from #325, it seems that it's the same problem. I don't have a way to reproduce for now.

**Comment by domialex** [comment]
I haven't had the bug since 0.7.2, so I'm closing this.
