### ISSUE TITLE
Slowdown when Sidekick crashes

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#295]
Sidekick crashing is fine, but the slowdown is dangerous, especially if the players are in hardcore.
It must be happening in the OnExit and the Hotkeys.
@leMicin @pobiega Do we try/catch the global in order to log uncaught exception?

**Comment by pobiega** [comment]
Don't think so, but thats obviously something we should do.

**Comment by leMicin** [comment]
Do we add try catch blocks everywhere a user can make an action? Events handler, Every clicks, etc.

**Comment by pobiega** [comment]
Ideally we would have an "outermost" try catch that will catch any exception, simply to log it before forcing a shutdown (if we want to handle it gracefully, it should be caught closer to the source). That way people can send their logs to us and we can figure out why crashes are happening.

**Comment by domialex** [comment]
I'm going to need help with this. No matter what I try, as soon as we subscribe to hook.MouseWheelExt with Hook.GlobalEvents() and the app crashes, it creates the lag.
Any ideas? (Never crash ;))

**Comment by domialex** [comment]
Fixed with #301.
