### ISSUE TITLE
GlobalHookMouseScrollHandler makes debugging very slow and causes lag

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#30]
It seems that when there is a mouse hook with Gma.System.MouseKeyHook, debugging gets extremely slow and it's hard to use the mouse.
Will need to experiment with custom made mouse hook and test if the lag still persists. This would remove the dependence on globalmousekeyhook. #29

**Comment by TheAtomicOption** [comment]
http://the-witness.net/news/2012/12/finding-and-fixing-a-five-second-stall/

**Comment by domialex** [comment]
My mouse (G502), has a free scroll wheel and if I spam the scroll wheel action, it seems to trigger lag in my Windows. I even hear a beeping sound...I'm not sure if the library used or simply the Windows API behind the scenes is the problem.

**Comment by dsolymosi** [comment]
I don't have this issue but I can recreate it with an AutoHotkey script spamming mousewheel.

**Comment by domialex** [comment]
Other bug, while closing Sidekick, there is some mouse lag also before it shut downs.

**Comment by trimbe** [comment]
This is probably unavoidable - https://stackoverflow.com/a/22130493

The lag on exit may be related to globalmousekeyhook though.

**Comment by domialex** [comment]
#90 Another example.

**Comment by domialex** [comment]
The lag on exit is back with the latest commit for #97. I know it's not done, just wanted to keep a reminder here.
