### ISSUE TITLE
[Wiki] Adjust wiki service to handle currencies, gems, etc.

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#306]
Wiki service should support base item, currencies, gems, etc.

**Comment by emrearapoglu** [comment]
If we could get "Item Info script-like" feature, it would be neat. For example, when you CTRL+C, show weapon pdps, edps, dps etc. for gems, show what quality does. we could also have "where div card drops" feature. 

Also, when you CTRL+C currencies in your tab, it should show how much are they worth in Chaos Orbs or Exalted Orbs. For example, if i CTRL+C on Alchemy Orbs in my currency tab, it should show me how much are they worth in Chaos Orbs.

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
