### ISSUE TITLE
Add cache for quicker initialization

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#308]
When the leagues change, we need to clear the cache to force a new download. My theory is that items and modifiers do not change during the course of a league, so we can cache that information.

Long initialization is becoming an issue with the recent filters, pseudo filters.

**Comment by Newbrict** [comment]
Is there a way to check version of the game running? you can always recache on new version

**Comment by leMicin** [comment]
We may be able to check indeed. So on every patch, we would refetch the data instead of every league. This would be better indeed.

**Comment by stormbringer766** [comment]
Could just do something like poe trade macro does. Build the data files and check them into the repo. On load, check for a new version, and only re-download files that have changed. It is an API hit but most of the time should be much faster. 

You can get really anal and have a process that downloads that data everyday, checks for changes and pushes them automatically. 

Anyone have a server at work they can hi-jack?

**Comment by leMicin** [comment]
We are stubborn so far in our goal to not have static data in our code. We would need to update the static files every time there is a new patch. That is not our goal. We want to use official APIs only (or as much as possible).
