### ISSUE TITLE
Discord info?

### ISSUE THREAD

**Issue by bgriffs** [domialex/Sidekick#312]
Any chance the wiki can get updated with the Discord info? Now that advanced search is in I want to help test Sidekick and discord seems like a good avenue.

**Comment by Dai-Katana** [comment]
Link to Discord is at the very bottom of the wiki. https://discord.gg/H4bg4GQ

**Comment by bgriffs** [comment]
Yeah, I see it on the readme now. Seems like the wiki should probably be updated as well though to be a more complete set of documentation. Just some thoughts.

**Comment by domialex** [comment]
@bgriffs Don't hesitate to edit the wiki if you have any ideas. We're always looking for some good help.
