### ISSUE TITLE
Show more information in the item preview

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#318]
- [x] Weapon DPS
- [x] Phys DPS
- [x] Elemental DPS
- [x] Armour at max quality
- [x] Evasion at max quality
- [x] Energy shield at max quality
- [x] Influences

**Comment by leMicin** [comment]
Begun in #327

**Comment by WhiteSammy** [comment]
What about if Fated?

**Comment by Newbrict** [comment]
I dunno if it helps but dps can be calculated with (min + max)/2 * aps

**Comment by leMicin** [comment]
It doesn't in this case as in the item preview, the data is already sent to us by the API. We just need to show it.
