### ISSUE TITLE
Search for "Death Nails" glove not working

### ISSUE THREAD

**Issue by vtroboguy** [domialex/Sidekick#321]
When searching, it pulls up "Death" not the full item

**Comment by leMicin** [comment]
This might be fixed by #320 . We will try to make a patch for it soon.

Can you paste the item here?

**Comment by vtroboguy** [comment]
Yes..sorry new-ish .. how do I link outside of POE?

**Comment by leMicin** [comment]
You can Ctrl+C when your cursor is over the item in the game. It will copy the text information. Then you can paste it here. It is how sidekick tries to understand what the item is. Sometimes we get it wrong.

**Comment by vtroboguy** [comment]
Rarity: Rare
Death Nails
Assassin's Mitts
--------
Evasion Rating: 104
Energy Shield: 20
--------
Requirements:
Level: 58
Dex: 45
Int: 45
--------
Sockets: G 
--------
Item Level: 61
--------
+18 to Intelligence
+73 to maximum Life
+14% to Lightning Resistance
0.23% of Physical Attack Damage Leeched as Mana

**Comment by leMicin** [comment]
Thank you!, that is perfect :)

**Comment by vtroboguy** [comment]
Here's another similar issue 
Rarity: Rare
Blight Cut
Cobalt Jewel
--------
Item Level: 68
--------
+8 to Strength and Intelligence
14% increased Spell Damage while Dual Wielding
19% increased Burning Damage
15% increased Damage with Wands
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

**Comment by vtroboguy** [comment]
That one searches as "Blight"

**Comment by leMicin** [comment]
This is indeed a bug that needs correcting for 0.7.2 Thanks for the report. We will try to fix it soon.

**Comment by vtroboguy** [comment]
I will add any other weird searches to this bug report I find!

**Comment by vtroboguy** [comment]
Rarity: Rare
Blight Buckle
Chain Belt
--------
Requirements:
Level: 48
--------
Item Level: 72
--------
+15 to maximum Energy Shield (implicit)
--------
+59 to Armour
+30 to maximum Life
+37% to Fire Resistance
16% increased Stun Duration on Enemies
20% increased Flask Effect Duration

**Comment by vtroboguy** [comment]
Rarity: Rare
Rapture Bane
Viridian Jewel
--------
Item Level: 74
--------
7% increased Attack Speed with Bows
+16% to Critical Strike Multiplier with Lightning Skills
+13% to Cold Resistance
19% increased Damage with Bleeding
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

**Comment by vtroboguy** [comment]
Rarity: Rare
Vortex Smasher
Opal Sceptre
--------
Sceptre
Physical Damage: 49-73
Elemental Damage: 27-55 (augmented)
Critical Strike Chance: 6.50%
Attacks per Second: 1.25
Weapon Range: 11
--------
Requirements:
Level: 60
Str: 95
Int: 131
--------
Sockets: B R-R 
--------
Item Level: 72
--------
40% increased Elemental Damage (implicit)
--------
37% increased Spell Damage
18% increased Fire Damage
Adds 27 to 55 Fire Damage
+17% to Chaos Damage over Time Multiplier (crafted)

**Comment by vtroboguy** [comment]
Rarity: Rare
Death Charm
Citrine Amulet
--------
Requirements:
Level: 24
--------
Item Level: 71
--------
+16 to Strength and Dexterity (implicit)
--------
Adds 3 to 6 Physical Damage to Attacks
Adds 1 to 5 Lightning Damage to Attacks
12% increased Rarity of Items found
+15% to Fire Resistance
+20% to Cold Resistance

**Comment by leMicin** [comment]
This is fixed in 0.7.2, We will try to release later today.

**Comment by vtroboguy** [comment]
Awesome. I will stop adding to the list then.
