### ISSUE TITLE
Add "About" section to settings pane

### ISSUE THREAD

**Issue by bgriffs** [domialex/Sidekick#322]
Add an "About" page to the settings pane that shows the following information so the user is quickly aware of important information needed for troubleshooting as well as other useful things.

- Application Version
- OS Version
- Link to GitHub repo to submit bug reports
- Link to Discord
- Button to check for updates

**Comment by leMicin** [comment]
I like the idea, but I am not sure this belongs in the settings. I think creating a completely new window would be preferable.

**Comment by bgriffs** [comment]
I'm certainly not tied to it being in the settings, only suggested it there as it was the only current UI element in the program outside the in-game views. :)
