### ISSUE TITLE
Can't start Sidekick

### ISSUE THREAD

**Issue by PanAchy** [domialex/Sidekick#323]
I'm trying to start Sidekick and I can see that it's gonna start loading and then it just closes itself. This is what the log says: '2020-03-26 17:47:12.506 -05:00 [INF] Keybind Triggered - Close Window'

**Comment by domialex** [comment]
What was the problem in the end?

**Comment by PanAchy** [comment]
Turns out what happened is I already had it open and was trying to open a new one. The only the log would tell me was the line I mentioned in my initial post.
