### ISSUE TITLE
Make changes to the price view

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#327]
Currently I am noticing the following problems when price checking
- The window appears over the text of the item you are trying to price check. This means that comparing items requires you to move the price window.
- Moving the window is annoying as not all zones are draggable. This can't be fixed easily, but if we don't have to move the window at all, this becomes a non issue.
- We can't see all the mod text in the filters because it is too narrow.
- We can't see the original value of the item you are price checking in the filters.

My suggestions to fix these issues are
- Make the price view more vertical than horizontal
  - Move the filters over the list of results.
  - Move the item preview below the list of results
- Change the filter visuals. I would like the filters to resemble the item preview. But beside pertinent lines, there would be a checkbox. That checkbox would behave exactly as the it behaves currently.
- Make the popup always align with the side of the inventory, or the stash. We won't open on the position of the mouse cursor anymore

**Comment by SnosMe** [comment]
Looks like you are borrowing some design ideas from Awakened PoE Trade 🙂 
It will be interesting to see how you fit all things horizontally (because you also have item preview)

**Comment by domialex** [comment]
@SnosMe Hello!
In my opinion right now PoE-Overlay has a clever way to filtering, since it shows the item we're currently price checking and you can just re-use the same view to adjust values.

**Comment by bgriffs** [comment]
The one thing I wish the view in PoE-Overlay showed was the actual value of the stat on the item. Classic trade macro had a nice way of doing it that was [min value to search] - actual stat - [max value to search] that I liked.

**Comment by leMicin** [comment]
This is the new view for the prices. Any comments are welcome.
![image](https://user-images.githubusercontent.com/5131398/78311622-5a70cf80-751f-11ea-8666-9e8a2a5be05f.png)
