### ISSUE TITLE
Not Launching

### ISSUE THREAD

**Issue by Zerssco** [domialex/Sidekick#329]
Run .exe after using it a day before will not launch. where does this actually install or located files to on your PC? Feels like i have to find the files manually and remove the entire program and re download once a day to use. 

Does not generate a crash dump 

other then this fantastic app good work

**Comment by leMicin** [comment]
There is no installation, everything is inside the single .exe. We create additional Sidekick_settings.json and Sidekick_Log.log files.
Maybe you have it running? Check your processes. Might be related to #326

**Comment by leMicin** [comment]
We are also having issues where Windows identifies Sidekick as a threat (it is not). It could be blocking the program from running at all. #265

**Comment by igorcastroo** [comment]
I can no longer open the program "/

**Comment by Azokyen** [comment]
Same, just tried to open it and it wont. Checked task manager and added an exclusion to windows defender and still not oppening.

**Comment by leMicin** [comment]
A lot of users have complained here and on Discord about the application not launching. I created a separate issue with a temporary solution to anyone who encounters this problem.

Related issue: #344
