### ISSUE TITLE
Saint's Treasure shownig as Sai

### ISSUE THREAD

**Issue by bgriffs** [domialex/Sidekick#335]
The Saint's Treasure card is showing up in Sidekick as a Sai.

![image](https://user-images.githubusercontent.com/60064706/77938655-0f875b80-7284-11ea-977e-d2123ae14a8e.png)

**Comment by leMicin** [comment]
This is fixed by #327 (It is in the branch features/327-price-view). I will leave open while the branch is not merged in develop.
