### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by AkaliSucks** [domialex/Sidekick#342]
[Sidekick_Log20200405.log](https://github.com/domialex/Sidekick/files/4435725/Sidekick_Log20200405.log)

it doesnt work and when i try to left click the icon in taskbar nothing happens and then it has the fatal error

"A fatal error occured and Sidekick is unable to recover. The error has been logged to a log file where Sidekick is installed, please report this error on https://github.com/domialex/Sidekick and attach the logs."

**Comment by leMicin** [comment]
As discussed on Discord with this user, we sent an Alpha build of the next version of the application. That fixed the issue.

Related issue: #344
