### ISSUE TITLE
v0.8.0-alpha

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#344]
There is an error that started happening for some of our users. The application just will refuse to launch. This error does not make any sense to any of the developpers. The application is compaining about a missing DLL from a self-contained executable.

We tried giving alpha versions of the application to some users who came to us on Discord with this issue. Their problem was gone. If you would like to give 0.8.0 Alpha a go, here is a download link
[Sidekick (OneDrive)](https://1drv.ms/u/s!AusbGardZ2xhgZ9lg--2fDEMV6zRQw?e=Q7OI7L)

If anyone has issues with this specific download, please comment in this issue or on Discord. Do not create issues for an unofficial version. Thanks

**Comment by WhiteSammy** [comment]
I have started having this issue, however, I don't get an error message. In fact, it literally says nothing and doesn't even show the loading popup that checks for updates.

Win10, tried restarting my pc, running as admin, and doing a fresh install. No dice.

**Comment by leMicin** [comment]
Did you try the download link for the alpha of 0.8.0?

**Comment by WhiteSammy** [comment]
Alpha branch no longer launches for me.

**Comment by bigk278** [comment]
0.8.0 has stopped working for me. Will not load.

**Comment by domialex** [comment]
@bigk278 Try the [latest official release](https://github.com/domialex/Sidekick/releases/latest/download/Sidekick.exe) again, I think there was a bug when we built those releases and I changed them recently.

**Comment by leMicin** [comment]
Closing this as we are getting nearer to an official release (and is no longer pinned)
