### ISSUE TITLE
Ctrl+scrollwheel deadzone on widescreen

### ISSUE THREAD

**Issue by dsolymosi** [domialex/Sidekick#35]
Depending on aspect ratio, a large deadzone where ctrl+scrollwheel is ignored can exist, to the right of the stash tab.

**Comment by dsolymosi** [comment]
As an addendum, I believe the window title/border is included in the extents calculations when in windowed mode, due to using `GetWindowRect`. Is `GetClientRect` better?

**Comment by domialex** [comment]
> As an addendum, I believe the window title/border is included in the extents calculations when in windowed mode, due to using `GetWindowRect`. Is `GetClientRect` better?

I've decided to make a quick fix and just suppress the original Ctrl+Scroll wheel entirely.
There is some problem with hooking the mouse though, #30 .
