### ISSUE TITLE
Add support for enchant sub-values

### ISSUE THREAD

**Issue by Newbrict** [domialex/Sidekick#352]
In my screenshot I put the correct search for cluster jewels (by the enchant slot on the item)

![image](https://user-images.githubusercontent.com/1683041/79132066-a28dbe80-7d77-11ea-86f1-b4a070344339.png)

**Comment by domialex** [comment]
For now Sidekick doesn't support sub-values, which are shown like this in the api:
![image](https://user-images.githubusercontent.com/4694217/79132327-1def7000-7d78-11ea-838c-a55bfa1104fd.png)

**Comment by Newbrict** [comment]
![image](https://user-images.githubusercontent.com/1683041/79375797-35209000-7f27-11ea-829e-25e2dcceff8d.png)
another case
