### ISSUE TITLE
Add a way to show item stats for items in own inventory

### ISSUE THREAD

**Issue by brynjolf** [domialex/Sidekick#356]
I saw you added Item stats to the listing. How do I show items in my inventory? Sometimes I want to compare DPS etc so it would be convenient for it to be it's own shortcut.

**Comment by domialex** [comment]
The part on the left of the overlay when you price check, is actually the item you're checking, in your inventory.
Can you clarify which information you're looking for that's not already there? Do you want the DPS to be shown for the **listed item**? If that's the case, the issue for that already exists here #318.
![image](https://user-images.githubusercontent.com/4694217/80030833-c0b19800-84b6-11ea-84ce-97f629790258.png)

If it's the DPS,

**Comment by brynjolf** [comment]
I meant more like POE Iteminfo, so you can CTRL + C and get some basic information about the item in your inventory, like this:
![image](https://user-images.githubusercontent.com/871342/80157651-f5ad1000-85c6-11ea-9e42-94f8cbffa41b.png)

**Comment by domialex** [comment]
The next version will already have some of this information. It's integrated into the main price-checking view.
