### ISSUE TITLE
Overlay position doesn't seem to take into account 2 displays in some cases

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#36]
[Image](https://imgur.com/a/y5p5mGf#w5McLO3)

**Comment by domialex** [comment]
I can't reproduce this, but I'm sure it's a real issue for some people. I will try again later, or someone else could hlep.

**Comment by vestakip** [comment]
Potentially related to windows desktop scaling, I have a 4K primary monitor scaled to 150% and a 1080p secondary at 100% and am able to replicate this. I am also able to get the overlay partially/fully off the bottom of both monitors when items are in the lower rows of my inventory.

**Comment by rwygand** [comment]
I have the exact same issue with a 4k monitor at 150% resolution.

**Comment by Log1x** [comment]
Same issue here. 4K @ 150%

**Comment by oliverw** [comment]
Same issue. Would be helpful to select a default monitor to display to the overview on.

**Comment by domialex** [comment]
It seems this happens with 2 monitors and a different dpi scaling.

**Comment by leMicin** [comment]
This seems to be fixed, I tried using my second monitor and it worked flawlessly.
