### ISSUE TITLE
[Trade] Adjust preview to support exchange queries

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#372]
![image](https://user-images.githubusercontent.com/4694217/80623709-9ca30900-8a18-11ea-982d-a5475cd3266f.png)
Related to #91.

**Comment by leMicin** [comment]
Can you explain what you want for this issue? I am not sure I understand what needs to be done.

**Comment by leMicin** [comment]
Removed from 1.0.0

**Comment by domialex** [comment]
I don't remember exactly why this was created, but my guess is that someone asked to be able to see the quantities in the exchange.
![image](https://user-images.githubusercontent.com/4694217/85094770-94b44980-b1bd-11ea-8437-09ac16354420.png)

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
