### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by mabryant** [domialex/Sidekick#376]
Program crashes when right clicking on the system tray icon.  Attached is the log file.
[Sidekick_Log20200504.log](https://github.com/domialex/Sidekick/files/4578105/Sidekick_Log20200504.log)

**Comment by domialex** [comment]
Duplicate of #344. I'm pretty this is now fixed, you can try to [re-download the latest version](https://github.com/domialex/Sidekick/releases/latest/download/Sidekick.exe).
