### ISSUE TITLE
Can't open windows and settings crash

### ISSUE THREAD

**Issue by SmoofBrane** [domialex/Sidekick#377]
Hiya, I've just downloaded the 0.8.0-beta version last night, but ever since then I cannot open the search windows or go into the settings window. With some items the search window only flickers into existence for a millisecond, and for others it loads the window, but closes before any information can be shown.
I'm not running any other POE related (or otherwise) software which uses the same keybinds.

Log: [Sidekick_Log20200513.log](https://github.com/domialex/Sidekick/files/4620187/Sidekick_Log20200513.log)
The above is a clean log; I started Sidekick, let it complete its initialization and tried to open the settings menu. It then crashed and suggested I open an issue here and post the log.

If there is anything else I could provide to assist in fixing this issue, please do let me know.

**Comment by domialex** [comment]
It does seem to be the same problem we've had with other versions recently and randomly.
Can you test this version?

1. [Download Sidekick](https://mega.nz/file/smhQmIaB#NmvxE7GM4nRVOcRmn-iJKn3Z9-UgeDV0ocADKO3eE48) (this is not an official release, it's just a test)
2. [Download .NET Core 3.1 Runtime](https://dotnet.microsoft.com/download/dotnet-core/current/runtime) (only do this once)

**Comment by SmoofBrane** [comment]
Yeah, well there you go. I downloaded both, unzipped the one and installed the other, ran the .exe and everything is working perfectly again. I'll keep using this version, if that is okay with you (don't want to use private/personal builds without permission). Thanks for the quick response and the amazing support. <3

**Comment by domialex** [comment]
I think next version I will include both builds, one self-contained, and the other smaller version if someone already has the .NET runtime.
