### ISSUE TITLE
Crash when pricing unidentified maps

### ISSUE THREAD

**Issue by Reaver01** [domialex/Sidekick#38]
Log states hotkey pressed and then program CTD. 

Map:
```
Rarity: Magic
Jungle Valley Map
--------
Map Tier: 1
--------
Item Level: 66
--------
Unidentified
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
```

Repeatable with other maps as well:
```
Rarity: Magic
Defiled Cathedral Map
--------
Map Tier: 14
--------
Item Level: 84
--------
Unidentified
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
```

**Comment by domialex** [comment]
Fixed by a4f710a0173a2abc98fa2cec0a36510d9f665596

**Comment by domialex** [comment]
Magic items are not supported yet, I simply made it so it doesn't crash for now.

**Comment by Reaver01** [comment]
Was this included in the latest release? I am on the latest and it's still doing it.

**Comment by domialex** [comment]
This release? https://github.com/domialex/Sidekick/releases/tag/v0.2.0-beta

**Comment by Reaver01** [comment]
that's the one. just installed it and went to try out pricing maps

**Comment by domialex** [comment]
It works here.

**Comment by Reaver01** [comment]
Well it doesn't work here. Issue is not resolved lol. Don't know what to tell you.

**Comment by domialex** [comment]
Lol Ctrl+C on the item and paste its code here please.

**Comment by vestakip** [comment]
Doesn't cause a crash for me
`Rarity: Magic
Ashen Wood Map
--------
Map Tier: 2
--------
Item Level: 83
--------
Unidentified
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
`

**Comment by domialex** [comment]
Closing this then, I'm pretty sure it's fixed.
