### ISSUE TITLE
[Chat] Leave Party - Create a modal window to quickly enter a character name

### ISSUE THREAD

**Issue by Calyx-** [domialex/Sidekick#381]
Hey, I generally have a few characters per league that I bounce between, so having to load up the settings menu to type in the character name to kick is quickly irritating.

My suggestion would be a modal window displaying a clickable list of the previous character names the user has entered, and a text box to enter a new name.

Then the ability to bind this to a key for quick swapping without loading the settings menu.

**Comment by Blinke** [comment]
As far as I can tell, the only times the logs mention the player's name is on level up and on death. In all other cases the logs refer to the character as "you".

**Comment by leMicin** [comment]
Indeed, this is not possible. It may be out of scope for 1.0.0 then.

The solution would be to have a list of remembered user names in the settings. And make the settings available in game, through a hotkey.

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
