### ISSUE TITLE
Elemental + Chaos resistance crafted mod doesn't recognize the elemental part

### ISSUE THREAD

**Issue by DanutMS** [domialex/Sidekick#382]
Posted this on reddit and was told to post it here. When pricing items with ele + chaos crafted resistance the elemental part is not considered when checking the total elemental resistance on the item. Both resists are considered when checking for all resistance though.

I've uploaded a [screenshot](https://i.imgur.com/YpY34R6.png) of the search box of the item, which shows the same value for all elemental resistance as it does for lightning resistance, even though it later recognizes that the item also has fire resistance. 

Item text:
```
Rarity: Rare
Empyrean Goad
Legion Boots
--------
Quality: +20% (augmented)
Armour: 125 (augmented)
Energy Shield: 24 (augmented)
--------
Requirements:
Level: 67
Str: 54
Int: 54
--------
Sockets: R-B-B-B 
--------
Item Level: 84
--------
70% increased Mana Regeneration Rate if you've cast a Spell Recently (enchant)
--------
+67 to maximum Life
14% increased Rarity of Items found
+47% to Lightning Resistance
30% increased Movement Speed
+15% to Fire and Chaos Resistances (crafted)
```

**Comment by leMicin** [comment]
Hi thanks for the report. It will be fixed in the next version.
