### ISSUE TITLE
Incursion Overlay Cut Off

### ISSUE THREAD

**Issue by BuchholzTim** [domialex/Sidekick#396]
### Issue
The Incursion Overlay is cut off at the end, so the last two entries are not visible.

#### Screenshot of Issue
![incursion](https://user-images.githubusercontent.com/25686940/84932595-d3baa000-b0d4-11ea-9d00-f5153bcb7e95.jpg)

#### How it should look like
![image](https://user-images.githubusercontent.com/25686940/84932650-e59c4300-b0d4-11ea-8969-d5cd94a7610d.png)

#### System Information
OS: Windows 10
Monitor: 34" Ultrawide, 3440x1440

#### Current "Workaround"
Change Windows-Scaling from your current value to something lower. In my case from 150% -> 125%

![JhN6L7p](https://user-images.githubusercontent.com/25686940/84933097-a6babd00-b0d5-11ea-9cc8-09ad78bd591f.jpg)

#### Better Solution
Add Option to scroll through the List.

**Comment by leMicin** [comment]
It should be fixed for the 1.0 release (Harvest league). Thanks for the feedback

**Comment by leMicin** [comment]
Related to #386
