### ISSUE TITLE
Multiple Language Support for Sidekick's UI

### ISSUE THREAD

**Issue by Zalhera** [domialex/Sidekick#40]
Add translations for multiple languages (same as POE Client languages).
Preffered language could be choosen at first start and saved in a config.json file.
Language could be changed through future settings menu in tray icon.
Related to #4

**Comment by domialex** [comment]
Implemented by #52

**Comment by domialex** [comment]
This feature would probably use [resources files](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1) and be able to replace the static files brought by #52.

**Comment by Zalhera** [comment]
Implemented with #108
