### ISSUE TITLE
Fix flicker with Vulkan renderer

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#406]
There seems to be a fix possible. By looking over at POE-Lurker, we can maybe make the same fix.

https://github.com/C1rdec/Poe-Lurker/blob/9649b9d29740ed1e9989c9c78b1a2a25b2a3b213/src/Lurker/Helpers/DockingHelper.cs
RemoveWindowBorder()

**Comment by domialex** [comment]
I don't have this anymore? Was it fixed for everyone?

**Comment by leMicin** [comment]
My friends and I don't have this issue also.
