### ISSUE TITLE
[Trade] Generate a whisper message to buy items from sellers

### ISSUE THREAD

**Issue by Jinuskeya** [domialex/Sidekick#41]
The possibility to select one of the sellers and get an @.whisper message. Removing the need for having a Chrome tab open, but the tool creating the whisper for you. Would that be possible?

**Comment by cmos12345** [comment]
I think that this would be a great feature, however currently there is no way to just search for items in Sidekick without having an item already in your inventory. 
I’m not sure if this is within the scope of this tool, but I think it would be a great feature

**Comment by Yureii** [comment]
Why would you want to buy an item when you already have it in your inventory ?

**Comment by Jinuskeya** [comment]
- Additional Divination Cards
- Additional Currency Items
- Min-Maxing Statistics on Items
- Additional Fun-to-play Maps
- More Fossils & Resonators for Crafting
- More Essences for Crafting
- More Scarabs for Farming

**Comment by Yureii** [comment]
You've thought about it way more than I did ahah. It feels like this belongs in a full blown trade companion and not just a lightweight trade macro ? As @cmos12345 said it might not be within the scope of this tool. I'd rather have a light macro myself but i do hope you get the features you want

**Comment by SitDownBe** [comment]
I can imagine a light-weight implementation of this, something like:
- Press CTRL + D on a divcard to get prices and sellers
- Click on the name of the seller to copy a trade message, then paste into chat
- **OPTIONAL:** send the trade message immediately after clicking
No clear indicator that the feature exists, but no additional clutter.

**Comment by cmos12345** [comment]
I feel like this issue needs more discussion / a clearer understanding of what Sidekick is supposed to be.

If Sidekick aims to be the "one in all" tool you will have to use, we'll eventually have to add a whole trading UI aswell and not just for incoming trades, but for outgoing trades (buying stuff) aswell.

For outgoing trades, I would just implement a webbrowser, that opens the pathofexile.com/trade website, and if you click on a whisper link, the whisper should automatically be created in Path of Exile.

For incoming trades, I would suggest we'd implement a UI like POE Lurker does. Which basically just means scanning for incoming whispers and creating buttons.

**Comment by domialex** [comment]
My goal was indeed to be the one in all tool., but only for incoming trade requests. This feature would only be needed for bulk exchanges I guess.

**Comment by leMicin** [comment]
I think having the feature of searching the trade from scratch inside the Sidekick would be cool. But it is a feature for later versions I think.

For 0.5, I would do this only for price check results. It would be most useful for bulk items, but it could be useful for normal items also.

**Comment by leMicin** [comment]
The whisper message is already included in the official API. We just need a button and to call clipboard.SetText . It is very easy to do.

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
