### ISSUE TITLE
DPS Tooltip "X%" Decrease / Increase

### ISSUE THREAD

**Issue by Jinuskeya** [domialex/Sidekick#42]
This is a far shot! So I don't think it's possible. But the possibility to see if an item listed will actually increase my DPS by "X%"? Per example, I run a Starforge with 497% Phys DPS. and a low 5% attack speed roll. It would be nice to see if there are better items on the market in the blink of an eye. 

If a value was returned were a Starforge with 495% Phys DPS, but 6% attack speed would boost or decrease my DPS with "X%". It does require some math, so I believe this to be quite a far shot.

**Comment by metroid112** [comment]
I think it's a nice feature but I think it'd be easier if you just used Path of Building for that since DPS calc is complex. You can always ask for some kind of integration.

**Comment by domialex** [comment]
It's indeed easier and faster to simply Ctrl+C the item, and paste that into Path of Building. If more people request I'll be surprised! We'll see.
