### ISSUE TITLE
Price Prediction is not available in other languages

### ISSUE THREAD

**Issue by dydrkagksdyd** [domialex/Sidekick#421]
I'm a Korean user using this application

I just recognized that price prediction is not working even I enabled the option.

Is it unavailable in Korean?

![image](https://user-images.githubusercontent.com/67371010/85544928-6bc90400-b656-11ea-96a7-4f945e38e04a.png)

**Comment by domialex** [comment]
The price prediction comes from https://www.poeprices.info/ which only supports English unfortunately. Just a reminder that the price prediction is not very accurate, it's only there to help a little bit.
