### ISSUE TITLE
[Cheatsheets] Keep cheatsheets window open

### ISSUE THREAD

**Issue by TotallyAFlareon** [domialex/Sidekick#436]
Unsure if this has been suggested before, but maybe add a option to keep the syndicate board up, Behind path of exile, that way it's a quick alt tab away, or able to be dragged and kept on a second screen.

**Comment by domialex** [comment]
Right now we close every window when using the price check, map mods or cheat sheets. I agree it would be useful to have the cheat sheets opened in another monitor for example.
We probably should only close the currently called window if it's already opened.
