### ISSUE TITLE
Trade API Documentation

### ISSUE THREAD

**Issue by Zalhera** [domialex/Sidekick#44]
Create documentation about how to query the trade API (with examples) or create the documentation on the offical [PoE Wiki](https://pathofexile.gamepedia.com/Path_of_Exile_Wiki) so that it's easier to contribute to the project.

**Comment by domialex** [comment]
This would probably be a file in `/docs`.

**Comment by leMicin** [comment]
I added a section in the wiki with the link the the swagger.
