### ISSUE TITLE
[Trade] Private League Support

### ISSUE THREAD

**Issue by rwygand** [domialex/Sidekick#449]
Hello! In Heist I'm playing is a private league along with 2000 of my closest friends. Sidekick is fantastic, but doesn't support this GGG feature. Private leagues show up at http://www.pathofexile.com/trade as a league (next to Heist, Heist SSF, Heist HC, etc), if your character is in that league.

![image](https://user-images.githubusercontent.com/186374/93720826-9258e700-fb40-11ea-83eb-74248f57929f.png)

If would be fantastic if I could select this league in Sidekick so that I'm seeing the most correct prices!

**Comment by rwygand** [comment]
JSON League Data:

`[{"id":"Standard","realm":"pc","description":"The default game mode.","registerAt":"2019-09-06T19:00:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/71278","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true,"rules":[]},{"id":"Hardcore","realm":"pc","description":"A character killed in the Hardcore league is moved to the Standard league.","registerAt":"2019-09-06T19:00:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/71276","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true,"rules":[{"id":"Hardcore","name":"Hardcore","description":"A character killed in Hardcore is moved to its parent league."}]},{"id":"SSF Standard","realm":"pc","description":"SSF Standard","registerAt":"2019-09-06T19:00:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/1841357","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true,"rules":[{"id":"NoParties","name":"Solo","description":"You may not party in this league."}]},{"id":"SSF Hardcore","realm":"pc","description":"SSF Hardcore","registerAt":"2019-09-06T19:00:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/1841353","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true,"rules":[{"id":"Hardcore","name":"Hardcore","description":"A character killed in Hardcore is moved to its parent league."},{"id":"NoParties","name":"Solo","description":"You may not party in this league."}]},{"id":"Heist","realm":"pc","description":"Hire a crew of thieves then plan and execute elaborate Heists to steal valuable rewards.\n\nThis is the default Path of Exile league.","registerAt":"2020-09-18T17:30:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/2936817","startAt":"2020-09-18T20:00:00Z","endAt":"2020-12-07T21:00:00Z","delveEvent":true,"rules":[]},{"id":"Hardcore Heist","realm":"pc","description":"Hire a crew of thieves then plan and execute elaborate Heists to steal valuable rewards.\n\nA character killed in Hardcore Heist becomes a Standard character.","registerAt":"2020-09-18T17:30:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/2936824","startAt":"2020-09-18T20:00:00Z","endAt":"2020-12-07T21:00:00Z","delveEvent":true,"rules":[{"id":"Hardcore","name":"Hardcore","description":"A character killed in Hardcore is moved to its parent league."}]},{"id":"SSF Heist","realm":"pc","description":"SSF Heist","registerAt":"2020-09-18T17:30:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/2936831","startAt":"2020-09-18T20:00:00Z","endAt":"2020-12-07T21:00:00Z","delveEvent":true,"rules":[{"id":"NoParties","name":"Solo","description":"You may not party in this league."}]},{"id":"SSF Heist HC","realm":"pc","description":"SSF HC Heist","registerAt":"2020-09-18T17:30:00Z","url":"http:\/\/pathofexile.com\/forum\/view-thread\/2936838","startAt":"2020-09-18T20:00:00Z","endAt":"2020-12-07T21:00:00Z","timedEvent":true,"scoreEvent":true,"delveEvent":true,"rules":[{"id":"Hardcore","name":"Hardcore","description":"A character killed in Hardcore is moved to its parent league."},{"id":"NoParties","name":"Solo","description":"You may not party in this league."}]}]`

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
