### ISSUE TITLE
Quality of Life Adjustments

### ISSUE THREAD

**Issue by randompoetradehelper** [domialex/Sidekick#45]
Simple ideas to make both more user friendly and appealing. Plenty of ways to improve upon.

https://gyazo.com/ad9d7902c3670c33269ed399df36ada5

**Comment by rushtothesun** [comment]
That would look awful though.

**Comment by domialex** [comment]
@randompoetradehelper Thanks.
The UI is a work in progress, every feature that affects will have its own part in it. So for now I will close this and keep an eye out for having good UX/UI.

**Comment by rushtothesun** [comment]
> 
> 
> @randompoetradehelper Thanks.
> The UI is a work in progress, every feature that affects it will have its own part in it. So for now I will close this and keep an eye out for having good UX/UI.
> Anyone know a designer with free time lol?

The UI is already fine as it is. TradeMacro's UI is super barebones and everyone still uses it.
