### ISSUE TITLE
Add Heist Cheat Sheet to F6

### ISSUE THREAD

**Issue by Chiron1991** [domialex/Sidekick#452]
Somebody on Reddit made a graphical cheat sheet for Heist rewards: https://www.reddit.com/r/pathofexile/comments/ixqmet/heist_cheat_sheet_11_originally_made_by/

Would be cool to add it to the existing cheat sheets in the F6 overlay.

**Comment by domialex** [comment]
The cheat sheets in Sidekick are not images, it's actually fields, texts and images, and translatable. So it requires a bit more time to implement.

**Comment by Chiron1991** [comment]
I'd like to tackle that, but I have absolutely zero experience with C#. I guess I could tinker a little by looking at the implementation of the other cheat sheets.
Is there any guide on how to setup a dev environment for this project? CONTRIBUTE.md doesn't say anything about it.

**Comment by RuriRyan** [comment]
Just install https://visualstudio.microsoft.com/downloads/ and open the sidekick.sln

**Comment by domialex** [comment]
There's a pretty big learning curve, don't worry about it. I'll do it if I have time. I'm trying to prioritize other things for now.

**Comment by RuriRyan** [comment]
i did a thing: https://i.imgur.com/uGVqpfJ.png
