### ISSUE TITLE
Cache Problem

### ISSUE THREAD

**Issue by RuriRyan** [domialex/Sidekick#453]
I was wondering why the trinkets stats didn't show up, but when I compiled everything locally it was working fine. Fixed it by deleting the settings, which also caused a cache reset I guess.
I would guess a lot of other people will also run into this and resetting the cache every once in a while might fix this.

Just digged through the code and saw there's a reset/clear when a new league is detected. But it looks like my cache was still missing the new mods.
I guess this can happen if you run sidekick before the new league actually launched, but when it's already present in the leagues api.

**Comment by domialex** [comment]
The cache was added in order to make Sidekick faster on launch. I'll tag this as a bug, until I think of a solution to prevent this.

**Comment by leMicin** [comment]
We are adding a button inside the settings that allows you to clear the cache manually. I don't think there is a way to fix this automatically
