### ISSUE TITLE
Cannot start version 1.0.3 application.

### ISSUE THREAD

**Issue by uKLEina** [domialex/Sidekick#454]
# Environment
Windows 10 1909
.Net Core Desktop Runtime 3.1.8 (also tested with 3.1.4)

# Step to reproduce
1. Turns off the anti-virus program(in my case, I disabled Norton's auto protection).
1. Start Sidekick version 1.0.2(it works well, without any problem).
1. It says "there's a newer version", so download 1.0.3 and overwrite already existed 1.0.2 application file.
1. Double click to start the 1.0.3 application.

# Expected result
Sidekick is successfully started.

# Actual result
Nothing happens. The application isn't started and there isn't any new line in the log file.

# Notes
I also tested with the following conditions:

- Delete the folder with the Sidekick application file completely and create a new folder, download 1.0.3 into it.
- Uninstall and re-install .Net Core runtime.
- Uninstall .Net Core runtime and install another version of .Net Core runtime.

In all cases, version 1.0.3 doesn't start. Normally when you start the application for the first time, it automatically creates some files s.t. Sidekick.db and Sidekick_Log, but with 1.0.3, those files aren't created. So I think it's process is instantly killed by something.

**Comment by domialex** [comment]
I know that Windows 10 shows a little warning when first starting an untrusted application, same thing happens with other tools. Can you try running as Administrator? Redownload the file to make sure it's a new file in the eyes of Windows.

**Comment by coresika** [comment]
Same issue like uKLEina here. I tried the redownloading and running as Admin under Windows 10. Still wont work.

**Comment by domialex** [comment]
Did you try both versions of the release? There's a zip file containing the runtime and the single-file executable.

**Comment by uKLEina** [comment]
I tried zip file version and it worked!
No need for admin privilege to successfully start it.

Thank you very much.
