### ISSUE TITLE
.Net Core not recognized

### ISSUE THREAD

**Issue by SmoofBrane** [domialex/Sidekick#464]
Hi, since yesterday the application hasn't been functioning correctly.
When I try to start the application I get an error saying:
> To run this application, you must install .NET Core
> Would you like to download it now?

However, I have already installed the new version, uninstalled and reinstalled, and repaired .NET Core.
The issue persists with the .exe, but the zip file version does start (as I took from another issue posted here).
However, since that version now also regularly stops working when using the Ctrl+Scroll tab switching,
I'd really like a solution to fix the standalone .exe.

Please do let me know if there is any information you need.
Since the standalone application doesn't even start I have no logs for it,
but the scrolling issue with the zipped version is attached [here](https://github.com/domialex/Sidekick/files/5287853/Sidekick_Log20200927.log).

**Comment by RuriRyan** [comment]
Could you try this file out: [Sidekick.zip](https://github.com/domialex/Sidekick/files/5287916/Sidekick.zip) ?
It's just a build/publish from the develop branch.

If you still get the problem it's likely something is wrong with your system, if not then there is a problem with the latest build and we may need a new one.

**Comment by SmoofBrane** [comment]
Hi, I literally just tried the .exe version and it just.. worked.
I didn't change anything, but it just started working again.
Literally no idea why, but it;s working so I guess I'll close the issue.

**Comment by domialex** [comment]
I've had this problem before, and I honestly have no idea why it happens.
When you run the single-file exe, it will extract in memory everything it needs to run, but it looks like sometimes something blocks it, without warnings.
Next time this happens, try to rename the file Sidekick.exe to another name like "Sidekick test.exe" and run it.
