### ISSUE TITLE
[WPF] Memory leak

### ISSUE THREAD

**Issue by Lightirius** [domialex/Sidekick#468]
Memory usage is climbing up after each price check or league view opening. 

It starts with about 126Mb (Which is a lot for a tool like this in my opinion) and constantly increases. 
Had it consume more than 1Gb of RAM after a long session and noticed only by the overall slowdown of price requests.
CPU usage also slowly increases from about 0 to 0.5-1% on an 8 core CPU when nothing is displayed.

To reproduce open and close league view or check a price for any item a few dozen times.

**Comment by domialex** [comment]
Thanks, I was aware of that for a while now. I'm guessing it's related to the WPF framework. I'm currently experimenting on trying to the UI of Sidekick to something more lightweight, but in the meanwhile if someone is able to pinpoint where the leak happens it would help.

**Comment by domialex** [comment]
Linked to #425.

**Comment by leMicin** [comment]
Found these links that explain the memory leaks problem in WPF. I will review all bindings to add BondingMode.OneTime where appropriate.

https://michaelscodingspot.com/ways-to-cause-memory-leaks-in-dotnet/
https://oz-code.com/blog/net-c-tips/top-3-memory-leak-inducing-pitfalls-of-wpf-programming

**Comment by leMicin** [comment]
I started looking into fixing memory leak issues with WPF. The solution would be to create Presentation models for every object that we want to show in the UI. These models ALL need to implement INotifyPropertyChanged. It is a lot of work right now and we would need to be extra careful in future development.

**Comment by leMicin** [comment]
We are moving away from WPF in 2.0.0. This will no longer be an issue.
