### ISSUE TITLE
Application completely died after crash, required re-download.

### ISSUE THREAD

**Issue by Brasolis** [domialex/Sidekick#469]
Just had the app crash while trying to price check an alt quality gem. After the crash, trying to open the app just gave an "You must install .NET core" error. I reinstalled .NET core, and restarted my computer but the issue persisted. I redownloaded (same version) and replaced the .exe in the same folder with the same database and JSON file and it works again fine.

Just letting you know there is something that completely kills the application.

**Comment by domialex** [comment]
Thanks, was it the .exe or the zipped version of Sidekick?
I'm going to close this since I've already given all the effort I could into trying to understand why this happens to some users, and I'm out of options :(.
I'm working on an alternative that might make this problem go away.

**Comment by Brasolis** [comment]
It was the .exe version. Sorry to hear this has been a continuing pain. 

Thanks for the great app though! GL in the future.

**Comment by domialex** [comment]
Fortunately, I haven't had any recurring issues reported for the zipped version.
