### ISSUE TITLE
Unable to run Sidekick

### ISSUE THREAD

**Issue by Ajsik24** [domialex/Sidekick#472]
Hey, so few hours ago everything was running fine and now when i start sidekick error shows up 

"A fatal error occured during initialization! This might be because the Path of Exile API service is down. Please try again later."

I am able to get the log and there it is

[Sidekick_Log20201016_002.log](https://github.com/domialex/Sidekick/files/5388745/Sidekick_Log20201016_002.log)

It doesn't tell me much im sorry if im doing something wrong here. I tried deleting the files and downloading the .exe version along with .zip i renamed the Sidekick.exe and nothing. 
What should i do? Thanks in advance

**Comment by domialex** [comment]
I've just released an update for this 😁.
