### ISSUE TITLE
[Trade] Handling Item Price Checking Delay

### ISSUE THREAD

**Issue by playmaker92** [domialex/Sidekick#473]
Hi,

Currently in the app, when I hover an item, and press CTRL+D, the window pops up and fetch the price automatically with a few seconds.

And there maybe a situation like this: 
If I got a rare item with some options, I need to decide to check/uncheck which options to get the price. But, after hitting a checkbox near the options, the app prints "Updating Shortly in 2 seconds" and fetch data after 2 seconds, even when I couldn't decide which options to select. So it could be wasting traffic.

So I want the app to enable configuring delay time myself when checking price of items. 

I think it is possible by doing one of these:
1) In setting menu window, place an input box to deal with DELAY TIME before fetching item price.
2) In setting menu window, place a toggle button which handles fetch item price AUTOMATICALLY or MANUALLY.
In AUTOMATICAL mode, the app works as it does so far. but in MANUAL mode, place a Search" button in checking item price window and does not fetch automatically.

**Comment by playmaker92** [comment]
Hi LeMicin, thanks for responding my opinion.
I have a question, when do I have to close this issue? I am not urging you but I do not know when I have to take an action.
Since this function will be added to the 2.x, I think this issue does not need to be opened no more.

**Comment by leMicin** [comment]
With version 2.0, we are changing our approach.

Magic and rare items will no longer search by default. You will have the option to select your filters and then start your search. This is to help in reducing the number of calls we are making to the official API. There will no longer be a timer that auto fetches after 2 seconds. This functionality is removed.

Other itmes which are less random, such as unique items, currency, etc. will search by default and fetch 10 results. Hopefully this is a compromise everybody will be happy with.
