### ISSUE TITLE
.NET core detection issues

### ISSUE THREAD

**Issue by umn-anon** [domialex/Sidekick#475]
Program would not launch, saying I didn't have the net core software installed. I uninstalled sidekick and reinstalled it and the issues fixed itself. Not sure how it detects the NET core but it seems to have lost track of it at some point.

**Comment by domialex** [comment]
Download the zipped version instead : https://github.com/domialex/Sidekick/releases/latest/download/Sidekick.exe

**Comment by leMicin** [comment]
We don't really have control on .Net Core detection issues as we are simply using Microsoft technologies. Hopefully, it will fix itself in a future .Net Core release.
