### ISSUE TITLE
program not running

### ISSUE THREAD

**Issue by umn-anon** [domialex/Sidekick#479]
It was working fine yesterday, but I closed it because the memory leak had gotten to about 500MB. Today I tried to run it and it refuses to launch. I redownloaded the exe and it didn't fix it, I restarted my computer and still no results, ran as admin, same thing. I get that this is a rather vague issue but if it has happened before then please let me know the solution before closing the issue.

**Comment by domialex** [comment]
Some people have been having this issue with the executable, it's a combination of multiple things here.
I suggest using the [zip version of Sidekick](https://github.com/domialex/Sidekick/releases/latest/download/Sidekick.zip), which as of now, has no problems.
