### ISSUE TITLE
NET Core Issue

### ISSUE THREAD

**Issue by mcurley32** [domialex/Sidekick#481]
Trying to run Sidekick and it says I need .NET Core even though I have it. I have already tried rebooting, reinstalling .NET Core, and running Sidekick in admin.  It's worked without issue since updating to v1.1.2 about a week ago, but now suddenly won't open. Any suggestions or fixes?

**Comment by leMicin** [comment]
Try downloading the zip version. Let me know if your issue is fixed.
https://github.com/domialex/Sidekick/releases/tag/v1.1.2

**Comment by mcurley32** [comment]
Yup, seems to have fixed it. Thank you.

**Comment by leMicin** [comment]
It is a known issue, a lot of users are having the same thing happen to them. We may start releasing only the zip version in the future. Glad you got it working again :)
