### ISSUE TITLE
Can't start on Windows 10

### ISSUE THREAD

**Issue by datrinh** [domialex/Sidekick#482]
I managed to start Sidekick when I tried it the first time. For some reason it doesnt work on subsequent tries... Added it to Antivirus already, but to no avail. It simply does nothing when I double click on the .exe

Anyone else facing similar problems?

UPDATE: Apparently the .zip version works for me. Will test it some more.

**Comment by domialex** [comment]
I will close this since it's probably related to the .NET single file issue.
