### ISSUE TITLE
App start is slow

### ISSUE THREAD

**Issue by nomis51** [domialex/Sidekick#498]
Is there any way to make the app start .. faster?
For me, it's literally taking between 30 sec to 2 minutes long to start, because it force me to wait for Poe.ninja cache to update... which i understand, but that's not happening with other price checking apps i've used. And, I think this is a very bad user experience for that kind of app.

Maybe use an "old" cache saved locally to start the app, then update it in a background task ?

There might be also other stuff that slows down the app start, but that's just what I see for now.

**Comment by leMicin** [comment]
This is fixed in the next version. We update the ninja cache only when you request an item. It will update in the background.

**Comment by leMicin** [comment]
We will release the next version in time for the new league :)
