### ISSUE TITLE
Use icons instead of text to show currency

### ISSUE THREAD

**Issue by Evilschnuff** [domialex/Sidekick#50]
You may want to change the abbreviation for jewellers orb ;)

![grafik](https://user-images.githubusercontent.com/12818606/72016858-d7fcaa80-3264-11ea-9c61-a996928de46d.png)

**Comment by domialex** [comment]
What needs to be done is maybe make everything chaos relative and allow the user to hover the price to see the original currency in full name.

**Comment by hseager** [comment]
> What needs to be done is maybe make everything chaos relative and allow the user to hover the price to see the original currency in full name.

Might be cool to show the currency as an icon and have the chaos relative price on hover

**Comment by domialex** [comment]
> > What needs to be done is maybe make everything chaos relative and allow the user to hover the price to see the original currency in full name.
> 
> Might be cool to show the currency as an icon and have the chaos relative price on hover

Thumbs up for real currency first and chaos relative on hover, thumbs down for the other way around.

**Comment by cmos12345** [comment]
So just to be sure. We want the actual currency first (as little icon). And show the chaos relative price on hover (with icon instead of text again)?

**Comment by domialex** [comment]
Something like that : https://i.imgur.com/jGrud8I.png
It should use the images from the `PoeCdnBaseUrl` in the provider, which I just realized it wrong for some providers. I will update that.

**Comment by domialex** [comment]
Remember to take into consideration the idea behind #91 for exchanges.

**Comment by hseager** [comment]
I thought it might be cool to have the icon for the currency instead of text like in the image below:

[https://imgur.com/4NCwOV5](https://imgur.com/4NCwOV5)

- Clear from a glance what the currency is
- Saves having to translate each currency text
- Saves UI space in that column
- Uses the same style as Poe Ninja + Poe Trade sites
- Can still have the coversion to chaos on hover of the icon

**Comment by domialex** [comment]
That's exactly what I'm aiming for, the first image was to test if the images from the cdn would load and if the tooltip could work.

**Comment by leMicin** [comment]
The tooltip part of this issue will be completed in #233
