### ISSUE TITLE
New version for new league(Ritual)?

### ISSUE THREAD

**Issue by Visteras** [domialex/Sidekick#500]
Hello! We cain wait new version for start Ritual league with new feature and new language?

**Comment by leMicin** [comment]
Hi, we are planning a maintenance release today to add some minor features and fixes for the new league. We will announce it on Discord when it is ready.

**Comment by leMicin** [comment]
The 1.2.0 version was released. We are not doing a big deal of the new version as there are some issues we want to fix before.
