### ISSUE TITLE
Price check shows no results

### ISSUE THREAD

**Issue by RiQuY** [domialex/Sidekick#503]
Im using Release v1.2.1, when doing price check with CTRL+D it shows results in blank on any item. I checked the configurations and I have everything set up, language, Ritual League and my char name.

![poe](https://user-images.githubusercontent.com/26349954/104829999-c683b080-5871-11eb-9fa4-3dbb5236d41c.jpg)

**Comment by domialex** [comment]
Can you click this link and paste it here?
![image](https://user-images.githubusercontent.com/4694217/104830025-35e4aa80-5848-11eb-91c1-887e69ece428.png)

**Comment by domialex** [comment]
I'm closing this, it seems even the official trade is not returning any items right now. Weird.
