### ISSUE TITLE
[Bug] No longer able to select Cluster Jewel Small Passives Grant X

### ISSUE THREAD

**Issue by Brasolis** [domialex/Sidekick#509]
Can no longer select what mods small passives grant on cluster jewels, making it useless for pricing them now. [Example](https://i.imgur.com/Yrj1utW.png)

Would also be great if we could force it to always search the "adds x passive skills" with the number it has as the max range instead of minimum as the number of passives added is a huge pricing factor.

**Comment by domialex** [comment]
Indeed, I've noticed that also.

**Comment by domialex** [comment]
Same with anointments.

**Comment by domialex** [comment]
Probably the same bug for map influences : 
![image](https://user-images.githubusercontent.com/4694217/106217461-492a3b00-61a3-11eb-9dd0-d91b97adb1d8.png)

**Comment by leMicin** [comment]
Fixed for 2.0
