### ISSUE TITLE
lutbot compatability

### ISSUE THREAD

**Issue by knasen88** [domialex/Sidekick#510]
hi, whenever running this program together with lutbot (invite, logout, /whois checkup etc) starts to break.
It wasn't always like this but rather after upgrading sometime this league it started occuring. Basically the invite macro and whois lookup breaks. (it takes the last whisperer and does either whois or invite) in the chat, really fast.

**Comment by domialex** [comment]
Is it because we added back the "Reply to latest whisper" feature since it was requested? @leMicin

**Comment by domialex** [comment]
@knasen88 Go into the settings and make sure there are no conflicts in the hotkeys with those you have in lutbot.

**Comment by knasen88** [comment]
i rebound cheat sheet cos it was conflicting and removed the reply to latest whisper function as i believe lutbot has it aswell ( it works for me without sidekick atleast) and its still happening

**Comment by eljoey** [comment]
I had the same problem when using the whisper replies. I fixed it by unbinding all the keybindings in the chat commands settings on sidekick.

**Comment by domialex** [comment]
I will close this since it seems it was just a hotkey conflict.
