### ISSUE TITLE
[Request] Sidekick fatal after trade api was rate limited

### ISSUE THREAD

**Issue by NDKilla** [domialex/Sidekick#513]
Looks like it might be expecting some data from the API and an object in a task ends up being null after the rate limit? Full log attached.
[Sidekick_log20210123.log](https://github.com/domialex/Sidekick/files/5860619/Sidekick_log20210123.log)

**Comment by leMicin** [comment]
We are reworking the way we call the API when we do a search. We are going to do a lot less automatic calls so the player has less chance of being rate limited.

**Comment by leMicin** [comment]
We are also including a new error message when there is an error from the API
