### ISSUE TITLE
Sidekick is incredible slow. 

### ISSUE THREAD

**Issue by Shadybliss** [domialex/Sidekick#516]
I moved to Sidekick from POE_trademacro because trademacro is inconsistent at fetching price checks and doesn't always work . But sidekick is slower. Im waiting for 2mins+ for some items to show any price.

Is this normal?

**Comment by leMicin** [comment]
We are using the official trade site. Which this league has been extremely inconsistent with speeds. At the moment of writing this comment, the official API is experiencing slowness. We can't speed up the official API unfortunetly :(

**Comment by domialex** [comment]
Another cause could be the known problem with the technology we use for the interface, WPF, a memory leak. Restarting Sidekick fixes this

**Comment by Shadybliss** [comment]
> Another cause could be the known problem with the technology we use for the interface, WPF, a memory leak. Restarting Sidekick fixes this



> We are using the official trade site. Which this league has been extremely inconsistent with speeds. At the moment of writing this comment, the official API is experiencing slowness. We can't speed up the official API unfortunetly :(



Hey thanks for the quick responses. 

I shall stick with it :) i really like the design of the UI and i really like the cheatsheet.
