### ISSUE TITLE
cannot choose league when starting sidekick

### ISSUE THREAD

**Issue by happybaby86** [domialex/Sidekick#517]
![image](https://user-images.githubusercontent.com/78040654/105880640-8e812800-603e-11eb-9e8f-c85f4b10cc81.png)
There is no option to choose a league, cannot use sidekick

**Comment by happybaby86** [comment]
after a few minutes the option shows again

**Comment by domialex** [comment]
It's not a bug with Sidekick, but the Path of Exile servers.
We just look for the information that is shown here : https://www.pathofexile.com/api/trade/data/leagues

And as you can see, it's very slow right now.

**Comment by happybaby86** [comment]
> It's not a bug with Sidekick, but the Path of Exile servers themselves.
> We just look for the information that is shown here : https://www.pathofexile.com/api/trade/data/leagues
> 
> And as you can see, it's very slow right now.

Thanks for your swift response!
