### ISSUE TITLE
Get 'pathofexile.com/trade' HASH

### ISSUE THREAD

**Issue by SmoofBrane** [domialex/Sidekick#532]
This isn't so much an issue report as a question.

I was wondering, out of personal interest, how you go from copying an item in game to get the official trade website hash.
I've been working on a website for personal use only and I want to dynamically generate search URLs for different items,
but to get those URLs I need the HASH.

If anyone could explain how you go from say "Tul's Breachstone" to "gYGK2hQ", I'd very much appreciate it!

**Comment by leMicin** [comment]
Hi,

To get search results, you need to do it in 2 steps. You must first generate your query with the API. That will give you the query id. In our code this is all done in : src/Sidekick.Infrastructure/PoeApi/Trade/TradeSearchService.cs . The method you call first is Task<TradeSearchResult<string>> Search(Item item, List<PropertyFilter> propertyFilters = null, List<ModifierFilter> modifierFilters = null);

This will give you a list of item ids and a query id. With those 2 information, you can then call the GetResults() method by passing those parameters.

Hope this helps you. If you need more help, come talk to us on discord :)
