### ISSUE TITLE
hideout command (f5) pasting clipboard data to chat

### ISSUE THREAD

**Issue by crosscutsaw** [domialex/Sidekick#545]
hello,

i find out this issue and i've encountered it multiple times. as i said in subject, hideout command pasting clipboard data to chat. maybe laggy environment could replicate this issue. 

thank you,
emre

**Comment by crosscutsaw** [comment]
you don't need it but i have a proof.png

https://i.imgur.com/KmEnw5Q.png

**Comment by leMicin** [comment]
Do you have the issue with version 2.0-unstable?

**Comment by crosscutsaw** [comment]
> 
> 
> Do you have the issue with version 2.0-unstable?

i've tested with that version and looks like the issue is fixed. thank you for your good work. i'm closing the issue.
