### ISSUE TITLE
Tray Menu Not Always Top-Most

### ISSUE THREAD

**Issue by Orichlol** [domialex/Sidekick#546]
![image](https://user-images.githubusercontent.com/15082948/113710615-ef1d8880-96b1-11eb-8074-80502c0df04f.png)

Tray menu sometimes is not top-most / visible above the Windows tray menu.

**Comment by leMicin** [comment]
I believe this is out of our control unfortunetly. We are using Electron for our tray menu and it looks like the issue is from their end.
