### ISSUE TITLE
[Cheatsheet] v2.0.0-unstable.277

### ISSUE THREAD

**Issue by sicu** [domialex/Sidekick#557]
'Cheatsheets' and 'sidekick options' forces win10 taskbar on top of the game. 'Map info' and 'check price' opens in an overlay as expected. Might be intended behaviour now that cheetsheets can be moved to other screens, but thought I'd check.

**Comment by leMicin** [comment]
I don't think we have a way to keep the taskbar hidden on "real" windows. The reason is as you said. It is to be easily movable between screens and also behave like a normal browser window (minimize, maximize, etc.)

**Comment by domialex** [comment]
We can make this configurable, overlay vs normal window.
