### ISSUE TITLE
price check doesnt work 

### ISSUE THREAD

**Issue by dydxo959** [domialex/Sidekick#567]
![dontknow1](https://user-images.githubusercontent.com/62172402/115131902-a01f0e00-a036-11eb-9f97-57b14b9365a5.png)
![dontknow2](https://user-images.githubusercontent.com/62172402/115131903-a2816800-a036-11eb-9176-e4fe80f9ae75.png)
![asdasfa4](https://user-images.githubusercontent.com/62172402/115132016-8df19f80-a037-11eb-8fbc-83b38441c4e2.png)

In 3.14, price check system doesn't work. Both in english and korean, both in 1.22 and 2.0 beta version

Also implement as administrator account

![sdfsdf3](https://user-images.githubusercontent.com/62172402/115131981-597de380-a037-11eb-93fd-1f8a944855e6.png)

**Comment by domialex** [comment]
Sidekick 1 hasn't been updated to support the new changes to the format of the pasted item.
Use the beta of Sidekick 2 instead, here: https://github.com/domialex/Sidekick/releases/tag/v2.0.0-unstable.283
