### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by cschsch** [domialex/Sidekick#57]
I strongly recommend adding tests to this project in order to minimize the risk of breaking functionality when changing stuff.

With the current state, it seems like some refactoring, as proposed in [this issue](https://github.com/domialex/Sidekick/issues/51), would help out a lot to make writing tests less painful.

**Comment by domialex** [comment]
Trying to stabilize a beta is not the best option for now.  Adding tests will make it more difficult to move code around and accept further PRs.
