### ISSUE TITLE
KeybindProvider.cs throwing an error in some cases

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#580]
Sentry is logging the following error for some users: `Collection was modified; enumeration operation may not execute.
`

![image](https://user-images.githubusercontent.com/4694217/115307986-0d669800-a138-11eb-90e7-6957925af236.png)

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
