### ISSUE TITLE
[Settings] Chat commands get reset upon restarting Sidekick

### ISSUE THREAD

**Issue by sicu** [domialex/Sidekick#587]
Version: Release v2.0.0-unstable.316 (and every version since .277)

- Chat commands are reset to default keybind when installing new update
- Custom chat commands are removed when installing new update
  _(all other customized settings/keybinds remain after update)_

**Comment by sicu** [comment]
The stored settings in `%appdata%\sidekick\Sidekick_settings.json` still has my previous customized keybinds and chat commands, so the program is pulling in default values from somewhere else for the entire 'Chat commands' page in settings after an update

**Comment by sicu** [comment]
Upon further investigation the issue appears not to be related to updating, but rather exiting Sidekick and starting it back up again. 

- Deleted Sidekick_settings.json ; forced the creation of a clean one when starting the program.
- Customized a few settings and keybinds on all pages and clicked save; verified that changes were committed to settings file.
- Verified that new keybinds work in-game.
- Exit and restart Sidekick; all pages in settings remain customized, except 'Chat commands' which is now reset to default. 
 (the settings file retains the custom settings, but they are not reflected in the program and do not work in-game)

**Comment by leMicin** [comment]
I have been able to reproduce this behavior. Thanks for the detailed report and investigation. We will look into it.
