### ISSUE TITLE
Sidekick not detecting/searching for items on my end

### ISSUE THREAD

**Issue by suikitetu** [domialex/Sidekick#60]
Hello ! I seem to have ran into a problem with Sidekick ^^
Tried to use it for the first time right now, but apparently I can't seem to make it work x) Can I get some help about why ? Thanks !
Here are some informations !

- Path of Exile version : 3.9.2
- Sidekick version : 0.5
- Other plugins/anything running on PoE at the same time : FilterBlade
- Scenario : Open Sidekick logs. Hover an item (Also tried with selecting it). Press Ctrl+D. 
- Result : Sidekick correctly asserts that it detected the command. However, it also states that it can't make sense of the item, and thus assumes it isn't an item.

Is it something that I'm doing incorrectly ? Or maybe, a problem coming from the recent 3.9.2 ?

Thanks a lot for the time and attention !

**Comment by Zalhera** [comment]
Could you Ctrl + C the item and paste it here?

**Comment by domialex** [comment]
@suikitetu Sidekick version 0.5? You mean [v0.2.0-beta](https://github.com/domialex/Sidekick/releases/download/v0.2.0-beta/Sidekick.v0.2.0.Beta.zip)?

What language of Path of Exile are you running? The latest beta only support English, but the next release will support all versions.

**Comment by suikitetu** [comment]
Apologies for the version error, I got confused with another item viewer also posted on reddit lately x)
Language may indeed be the issue as I am playing the game in non-English. I will get home in an hour, I'll switch to EN and let you know of the result !

**Comment by suikitetu** [comment]
Update : I tried with my PoE in english, and it worked without any issue ! 
I apologize for this fake bug report x)

**Comment by domialex** [comment]
Duplicate of #4
