### ISSUE TITLE
EF error while saving PoeNinja translations

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#609]
We should add more checks when trying to the save poeninja info:
```
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: NinjaTranslations.Translation'.
```

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
