### ISSUE TITLE
Items in Korean are not recognized.

### ISSUE THREAD

**Issue by ONDR** [domialex/Sidekick#614]
I'm trying to check the price of an item, but the item in Korean is not recognized.

**Comment by domialex** [comment]
Did you set the game language to Korean?
![image](https://user-images.githubusercontent.com/4694217/116186681-20f29f80-a6f2-11eb-86b2-7b7126b43486.png)

**Comment by ONDR** [comment]
Of course I did, but it wasn,t good. Applying the new patch works great. thank you
