### ISSUE TITLE
"Cosmetic": Language Settings in UI does not affect the Taskbar menu language

### ISSUE THREAD

**Issue by as69-github** [domialex/Sidekick#616]
Hi,
i wanted to report a small cosmetic issue.

The language for the taskbar symbol seems to use the OS language settings instead of the configured setting in the UI (at least for "settings" and "close" actions).

Taskbar Menu (is displaying German language)

![image](https://user-images.githubusercontent.com/74071772/116386105-c2c0dc00-a819-11eb-8013-e5f40f083b5c.png)

UI Language is set to English:
![image](https://user-images.githubusercontent.com/74071772/116386199-d704d900-a819-11eb-8186-96ba04e71a0c.png)

As this is by no means a big deal, feel free to do whatever you want with this reported issue :)

Just wanted to report it, as i am not sure how many people use English instead of their supported native language in the UI and may be confused (the menu is not that big, so i assume no one really has a problem with that).

A huge "Thank you" for your work on this project!

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
