### ISSUE TITLE
Map information feature

### ISSUE THREAD

**Issue by Martacus** [domialex/Sidekick#62]
A nice addon for Sidekick would be Atlas/Map information. Right now the map stash tab isn't very informative to what maps are where on the atlas and what special drops they have etc. Something like this would be a nice addition

**Comment by cmos12345** [comment]
I think this issue is obsolete with PoE patch 3.9.2c, isn't it?

**Comment by leMicin** [comment]
Yes, I believe so. The updated map stash is awesome.

**Comment by domialex** [comment]
A lot of tools are now obsolete with this patch lol.
