### ISSUE TITLE
Choose which item properties should be included in default search

### ISSUE THREAD

**Issue by Zalhera** [domialex/Sidekick#63]
Add option in future setting menu to choose and configure which properties should be included in the default Ctrl + D search.
Examples:
 - Always include influence on equippable items
 - Always include number of white sockets on item
 - etc.

**Comment by domialex** [comment]
The settings window would have default values.
The overlay window would, in the future, be able to open a new window to edit/view the current query. Just like POE-TradeMacro has but also able to add/remove attributes.

**Comment by leMicin** [comment]
Duplicate of #287 . The solution is slightly different than what was proposed here. It will be explained in #287
