### ISSUE TITLE
Cursor lag when scrolling

### ISSUE THREAD

**Issue by vhbert** [domialex/Sidekick#76]
When I run the app and I scroll anywhere on any window, my cursor seems to lag/stutter big time.
The duration of this lag depends on how long I scrolled beforehand.

Not sure if this is related to Issue #30 since I am not debugging anything

**Comment by domialex** [comment]
It's related to #30.
I'll need to look into it eventually. I might event disable the mousehook for the next beta until we find what's causing this. (Too many events?)
