### ISSUE TITLE
Fix TrayIcon Cross-thread operation not valid after changing language

### ISSUE THREAD

**Issue by domialex** [domialex/Sidekick#78]
I did this domialex@b27edead2a8388654ae2375bd5416bd91b16862c to at least support correctly fetching static data after changing language.
Right now this leaves the TradeClient and the TrayIcon in an not optimal situation in terms of stability if this re-fetch somehow fails.

https://github.com/domialex/Sidekick/blob/develop/source/Helpers/TrayIcon.cs#L37

1. Sidekick starts in English by default
2. TradeClient fetches English Public Trade API data
3. User price checks an item in another language
4. TradeClient fails on first try and item fetch is cancelled
5. TradeClient retries every minute

System tray notifications will be done twice though :(.

**Comment by leMicin** [comment]
@domialex Is this still an issue with all the work that has been done since?

**Comment by domialex** [comment]
Probably not since it was originally caused by having static classes waiting incorrectly other tasks.
