### ISSUE TITLE
Error when trying to exit and not sure how to config.

### ISSUE THREAD

**Issue by RichMoney** [domialex/Sidekick#80]
Basically I wanted to turn off the hideout macro since luttools has that, but when I couldn't find a config option I just right clicked the icon and exited.... it then started moving my mouse in game. 

https://clips.twitch.tv/PunchyRudeOrcaFreakinStinkin

**Comment by domialex** [comment]
That's a very bad bug indeed. I'm sorry about that, I'll look into it.

**Comment by domialex** [comment]
Related to #30
