### ISSUE TITLE
When price checking from Divination Card Stash tab the last item searched is shown instead

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#84]
When price checking from Divination Card Stash tab the last item searched is shown instead as search result.

You have to pull out the divination card and price check it from inventory.
When you put back the divination card into Divination Stash tab , and then price check again  - nothing shows . Not last searched , or even a blank window, just nothing. After that you cannot price check from divination stash tab at all.

I had no issues price checking from any other premium tab.

Also minor isuue - price checking on Organs does not work. There is just a blank window for a split second.

**Comment by domialex** [comment]
Thanks.
I was aware about the organ price checking, didn't have much time to investigate yet.

**Comment by trimbe** [comment]
This is because GGG doesn't support the Ctrl-C for item details feature in the Divination tab. Might be the same issue in the unique tab (I don't have one to check), since both are not the traditional item display.

**Comment by AwesomeFart** [comment]
i dont have Unique TAB either to confirm.

**Comment by eugenio-santos** [comment]
Unique Tab supports Ctrl+C and sidekick works there too.

**Comment by domialex** [comment]
We will need to find a way to not show the last item.

**Comment by domialex** [comment]
Fixed by #143.
