### ISSUE TITLE
[Chat] Add chat macros similar to trade companion

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#85]
You can test this only when somebody sends you copied messege from Trade web site.

**Macro 1** 
F1 - Invite buyer to party with a message ( later when settings is created msg can be edited )

> /invite %buyer%
> @%buyer% Come and get your: %item% listed for %price%

**Macro 2**
F2 - Sends request to trade with the buyer

> /tradewith %buyer%

**Macro 3**
F3 - Thank you , kick myself out . This will be more general - it writes in in local chat so it can be used for selling and buying, While the other player is near you. ( later when settings is created msg can be edited )

> Thank you
> /kick %myself%

User can then press F5 to go to hideout.

**Macro 4**
F4 - I am bussy pls wait. Message to buyer ( later when settings is created msg can be edited )

> @%buyer% Busy, just a sec pls or try again in 5 min - (%item% for %price%)

 **Macro 5** ( optional ) 
F6 - still interested in my item? Message to buyer  ( later when settings is created msg can be edited )
> @%buyer% still interested in my %item% listed for %price%  ?

I am not a programmer, but i love this project and just want to help so i atleast got you the basic macro setup that is needed for trading that should be fairly easy to implement - like the F5 you did.

I got this from Trades Companion - it should work . If %buyer%, %item%  is code from Trades Companion app and does not translate to game - then  i am sorry but i think you can pretty much use it like this, bcs trades companion just sends theese in the chat.
You can test this only when somebody sends you copied messege from Trade web site.

**Comment by domialex** [comment]
I wanted to eventually recreate what [MercuryTrade](https://github.com/Exslims/MercuryTrade) does.

**Comment by AwesomeFart** [comment]
this could be like "default option for players that dont want to setup stuff or are new" 
I can function on theese macros and dont need any other. Pretty sure most of players would.
Ofcourse it would be great to be able to create my own macros completly or have other features.

**Comment by AwesomeFart** [comment]
Mercury trade is very BIG addition to UI, TBH i would prefer not to have so many bars and stuff and just theese 4-5 macros. I understand there will be issue with multiple trades, that Trades companion solves by showing you BOX ingame with trade 1, trade 2 etc, that you can switch around. But this could be added in the future - Mercury trade has a similar thing aswell..

**Comment by domialex** [comment]
Everything is optional in the end so it's not a problem.

**Comment by leMicin** [comment]
Cleaned old issues. We are moving the project to https://github.com/Sidekick-Poe/Sidekick . If this is still something that you want, please create a new issue at that location.
