### ISSUE TITLE
CTRL + Click causes input delay/lag

### ISSUE THREAD

**Issue by bowsersoulstar** [domialex/Sidekick#90]
Beta 3.

I noticed when I was ctrl+clicking items over to stashes, the mouse movement starts to be delayed along with the clicks.  This causes a bit of an annoyance for those of us moving lots of items between inventory/stash quickly.  Confirmed Sidekick is the possible cause by attempting to replicate while Sidekick is not loaded.  

It only exhibits this behavior while sidekick is  #loaded.  I don't believe I noticed this in Beta 2.

**Comment by lascoin** [comment]
This is due to the scrollhook for scrolling stashtabs as in #30

**Comment by domialex** [comment]
Duplicate of #30.
