### ISSUE TITLE
Implement a view for currency results

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#91]
So price of 1 chromatic orb is "0,10752688" chaos.

What can player quickly deduct from this? - well i kinda suck at math so not much.

What information would be way more usefull for me?
**the actual first 10 listings as they are - 932 chromatic for 100 chaos**
 - that way i know i can sell stack of 93 for 10 - easy math. Much more faster for me. Which i would not deduct from 0,10752688.  This number can still be somewhere, or there could be the one from poe ninja. But let me see the actual fist few listings same as trade macro does it.

Imo this goes for all items in the currency tab and for splinters and oils, shards, (catalysts?).

![curre](https://user-images.githubusercontent.com/59807858/72251244-c9fcb000-35fd-11ea-94b9-48de19be1663.png)

**Comment by domialex** [comment]
Related to #50.

**Comment by domialex** [comment]
I'm going to close this since we now can see this information in the seller's item's preview.
![image](https://user-images.githubusercontent.com/4694217/79673489-39a7ab80-81a8-11ea-81bb-f533cc0cb26d.png)

**Comment by domialex** [comment]
It seems since we fixed the exchange query, we lost that information :
![image](https://user-images.githubusercontent.com/4694217/80623498-433ada00-8a18-11ea-9596-ed9d838c5507.png)
For now I don't think it's a problem, but I'll keep this information here.
