### ISSUE TITLE
Add price checking magic flasks functionality

### ISSUE THREAD

**Issue by AwesomeFart** [domialex/Sidekick#92]
When CTRL+D on magic flask, nothin happens, not even blank window.

CRTL+D works without issues on normal rarity flasks.

Since prefixes and suffixes matter on flasks, and there is not so many of them -  same as their combinations - it would be great if CTRL+D on magic flask would search for the exact same prefixes and suffixes when flask is magic - there will always be results and price prediction will be precise.

So when i CTRL+D on "Panicked eternal life flask of dousing" - it would search for Panicked eternal life flask of dousing NOT just eternal life flask.

**Comment by Zalhera** [comment]
Magic items of any sort are not supported in the current release.
Support for magic items will likely come in combination with advanced search

**Comment by leMicin** [comment]
This must wait until the Advanced search is complete. Too many changes inside the ItemParser will make too many conflicts

**Comment by leMicin** [comment]
This is fixed by #243
