### ISSUE TITLE
Sidekick does not work on Laptop

### ISSUE THREAD

**Issue by Rayj-byte** [domialex/Sidekick#93]
Hey, i use Sidekick since 0.2.0 on my Desktop PC at home and it works great. Now im at work and wanted to use my Laptop, but it doesnt work. i get logs i see sidekick in my taskbar, it says its rdy but when i press ctrl (tested both) and d, nothing happens, my skills switch so its not the buttons.

i tried to install framework but it says i allready got it on the laptop. tried to restart, tried to start sidekick before and after poe. got no idea whats wrong, hope u can help :D ty

edit
forgot to add, i checked my league, i also selected another league and switched back to metamorph
didnt help

**Comment by Zalhera** [comment]
Could you right click on the Sidekick Icon in tray and copy the logs from Show Logs?

**Comment by Rayj-byte** [comment]
13.01.2020 15:58:55 - Starting Sidekick.
13.01.2020 15:58:55 - Fetching Path of Exile trade data.
13.01.2020 15:58:55 - Fetching Leagues.
13.01.2020 15:58:56 - 4   Leagues fetched.
13.01.2020 15:58:56 - Fetching Static item categories.
13.01.2020 15:58:56 - 31  Static item categories fetched.
13.01.2020 15:58:56 - Fetching Attribute categories.
13.01.2020 15:58:57 - 9   Attribute categories fetched.
13.01.2020 15:58:57 - Fetching Item categories.
13.01.2020 15:58:57 - 13  Item categories fetched.
13.01.2020 15:58:57 - Path of Exile trade data fetched.
13.01.2020 15:58:57 - Sidekick is ready, press Ctrl+D over an item in-game to use. Press Escape to close overlay.

**Comment by Zalhera** [comment]
Is this the log after you tried to price check an item with Ctrl + D or before that?

**Comment by Rayj-byte** [comment]
before, now im ingame and try to check anything or use f5 for hideout

this is the log than

13.01.2020 16:12:42 - Starting Sidekick.
13.01.2020 16:12:42 - Fetching Path of Exile trade data.
13.01.2020 16:12:42 - Fetching Leagues.
13.01.2020 16:12:43 - 4   Leagues fetched.
13.01.2020 16:12:43 - Fetching Static item categories.
13.01.2020 16:12:47 - 31  Static item categories fetched.
13.01.2020 16:12:47 - Fetching Attribute categories.
13.01.2020 16:13:20 - 9   Attribute categories fetched.
13.01.2020 16:13:20 - Fetching Item categories.
13.01.2020 16:13:36 - 13  Item categories fetched.
13.01.2020 16:13:36 - Path of Exile trade data fetched.
13.01.2020 16:13:36 - Sidekick is ready, press Ctrl+D over an item in-game to use. Press Escape to close overlay.

**Comment by Rayj-byte** [comment]
got it
had to start it as admin

**Comment by joelrobichaud** [comment]
Had the same problem, running as admin worked.

**Comment by domialex** [comment]
I don't like that you have to do this, I'll need to look into it.

**Comment by eugenio-santos** [comment]
I did some testing and I think this happens when you launch poe as admin, in that case sidekick needs to be in admin mode as well.

**Comment by domialex** [comment]
Fixed by #105.
