### ISSUE TITLE
ALT + D not working

### ISSUE THREAD

**Issue by TeamCatalyst** [domialex/Sidekick#94]
ALT + D is not working for me on Unique / Rare Items. Tried in Stashes, Inventory and equipped Items.
F5 and ALT + W is working.
Pressing 2 times SHIFT + Z is not working either.

I'm using Windows 10 with 2 displays.
PoE is in Windowed Fullscreen mode.
Sidekick started with administrator permissions (from desktop).
.NET Framework 4.8 is installed.

Maybe I did something wrong?

**Comment by TeamCatalyst** [comment]
Oh my god. I press ALT + D. It is CTRL + D..... I'm such a PoE Trade Macro user haha

**Comment by domialex** [comment]
Related to #83.
