### ISSUE TITLE
Overlay Minimizes Path of Exile

### ISSUE THREAD

**Issue by MMMMMMCasserole** [domialex/Sidekick#95]
First, I'd like to thank you for creating this. It's very handy. Unfortunately whenever I price-check an item, the overlay opens and minimizes Path of Exile. 

I am playing in fullscreen. 

Thanks for your time!

**Comment by domialex** [comment]
You can't show an overlay while the game is in fullscreen mode, only in windowed and fullscreen windowed. The only way to support fullscreen would be to inject the PoE executable and that would be against the Terms of Services.

**Comment by domialex** [comment]
An alternative would be to show a tooltip like POE-TradeMacro does. But that tooltip would be very minimal with no interactions, an option maybe?
