### ISSUE TITLE
New code architecture - Multiple Projects, Dependency Injection

### ISSUE THREAD

**Issue by leMicin** [domialex/Sidekick#97]
# New code guidelines
## One class per file
One of the "Best practices" of C# is to limit files to only one class.

## Dependency Injection
All the new services will use Dependency Injection. The code base will be closer to the new DotNetCore standards for services.

# New structure
The first part is restructuring the code into multiple projects with clear separation. I suggest the following projects

## Sidekick.Core
This project contains core functionality to the rest of the projects. It includes helpers to initialize the Dependency Injection Provider and some type extensions. Code found in this project must be generic.

### New initializer
The new initializer allows 3 different hooks in the initialization pipeline. In order they are BeforeInit, Init, AfterInit. Data initialization will mostly be done in one of the first two hooks. The third hook is mostly used to give feedback to the user that the tool is ready.

This allows to clean some of the dependencies. For exemple, the TradeClient was the service that initiated the Tray message saying the tool is ready. It really didn't make sense as the TradeClient should only serve to get the trade data.

To use the new initializer, simply add one of these interfaces to your services : IOnBeforeInit, IOnInit, IOnAfterInit, IOnReset.

## Sidekick.Business
Contains services to handle the functionality of the tool such as parsing, evaluating, etc. This project could be split into multiple smaller ones if it becomes too big. (example: Sidekick.Parsers). We use a lot less static classes in favor of static services.

### Languages
- LocalizationProviders are renamed to Language. LocaleSettings is renamed to LanguageProvider.
- Removed LanguageEnum. With reflection we can find the right Language with a custom attribute. It will simplify Adding new languages to the tool, as all that will need to be done is creating one single file and no modifications inside the providers.

## Sidekick.Input
This project contains services to handle User inputs. It is closely tied with the UI project.

## Sidekick
This is the original project but stripped down to only the views. This project calls the Business and hooks into the Input project to keep the functionality.

### Legacy
There is currently a static class named Legacy in which there are static instances of classes resolved using Dependency Injection. This will have to eventually be removed and all code should use Dependency Injection from now on. I wanted to release a working "WIP" version as soon as possible so if anyone wants to help, they are welcome to.

# Current version
The current version only moved parts of the code. The goal is to move all code that is not strictly UI away from the UI project Sidekick.

The parts moved are:
- LanguageProvider
- TradeClient
- HttpClientProvider
- Logger
- ItemParser

## Refactor
In the past, I simply tried to move the code into the new projects and make it work. I now started refactoring the code that was previously moved. One of the exemples of this is the LeagueService. That code was previously inside the TradeClient. For contributers, the LeagueService is the exemple of what the new architecture code aims to achieve in terms of readability, maintainability.

# Next steps
- Move more code towards the new projects.
- Make sure all code uses Dependency Injection when possible.
- There is a lot of code moved that is not optimized for readability and maintenance. Exemples of this can be found inside the TradeClient where the TradeClient is notifying Windows.
- Reduce RAM usage to levels prior to this update. (to around 40 mb)

**Comment by Blinke** [comment]
I like the direction of this!

I'm not entirely sold on the benefits of handling the DI through attributes and reflection instead of the more traditional approach. It looks like a lot of extra complexity for the small convenience of not having to type out `services.AddSingleton` (or equivalent) for each class.

**Comment by domialex** [comment]
I'm concerned about the performance, I guess we would want to limit the namespace for those.

**Comment by leMicin** [comment]
The cost of doing it with the attributes is only on the app initialization. There is no cost once the app is running.
I think limiting the namespace for the search is a good compromise between the performance and the developper experience.
Whichever way we go from here, I don't really mind that much. We are going in a much more stable direction than we were a few days ago.

**Comment by domialex** [comment]
Ah I see, only on the app initialization. 👍
The implementation I have no opinions.

**Comment by leMicin** [comment]
Updated the issue with sections about the new initializer and refactor.

**Comment by leMicin** [comment]
This issue can be closed as discussed on Discord. We will split the remaining tasks into new issues.
